# General settings
title:        astomih

background:
  color:    rgb(43,42,51)

foreground:
  color:    whitesmoke

# Card info
card:
  name:       astomih
  titles:     "Software Engineer"

# Profiles
profiles:
  github:         astomih
  #youtube:        user/YouTube
  x:        astomih
  #instagram:      instagram
  #facebook:       facebook
  #linkedin:       company/linkedin
  #stackoverflow:  1
  #twitch:         twitch
  hatenablog:     https://astomih.hatenablog.com/
  email:          astomih.jp@gmail.com

# Others
markdown: kramdown