var g;var k;k||(k=typeof Module !== 'undefined' ? Module : {});k.ig||(k.ig=0,k.nh=0);k.ig++;
(function(a){function b(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onprogress=function(c){var e=b;c.total&&(e=c.total);if(c.loaded){d.pf?k.uf[a].loaded=c.loaded:(d.pf=!0,k.uf||(k.uf={}),k.uf[a]={loaded:c.loaded,total:e});var f=e=c=0,h;for(h in k.uf){var n=k.uf[h];c+=n.total;e+=n.loaded;f++}c=Math.ceil(c*k.ig/f);k.setStatus&&k.setStatus("Downloading data... ("+e+"/"+c+")")}else!k.uf&&k.setStatus&&k.setStatus("Downloading data...")};d.onerror=function(){throw Error("NetworkError for: "+
a);};d.onload=function(){if(200==d.status||304==d.status||206==d.status||0==d.status&&d.response)c(d.response);else throw Error(d.statusText+" : "+d.responseURL);};d.send(null)}function c(a){console.error("package error:",a)}function d(){function b(a,b,c){this.start=a;this.end=b;this.audio=c}function c(c){k.nh++;if(!c)throw"Loading data file failed."+Error().stack;if(!(c instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;c=new Uint8Array(c);b.prototype.eh=c;c=a.files;for(var d=
0;d<c.length;++d)b.prototype.requests[c[d].filename].onload();k.removeRunDependency("datafile_index.data")}b.prototype={requests:{},open:function(a,b){this.name=b;this.requests[b]=this;k.addRunDependency("fp "+this.name)},onload:function(){this.finish(this.eh.subarray(this.start,this.end))},finish:function(a){k.FS_createDataFile(this.name,null,a,!0,!0,!0);k.removeRunDependency("fp "+this.name);this.requests[this.name]=null}};for(var d=a.files,e=0;e<d.length;++e)(new b(d[e].start,d[e].end,d[e].audio)).open("GET",
d[e].filename);k.addRunDependency("datafile_index.data");k.Sg||(k.Sg={});k.Sg["index.data"]={ci:!1};n?(c(n),n=null):h=c}if("object"===typeof window)window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/");else if("undefined"!==typeof location)encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");else throw"using preloaded data can only be done on a web page or in a web worker";
"function"!==typeof k.locateFilePackage||k.locateFile||(k.locateFile=k.locateFilePackage,l("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var e=k.locateFile?k.locateFile("index.data",""):"index.data",f=a.pi,h=null,n=k.getPreloadedPackage?k.getPreloadedPackage(e,f):null;n||b(e,f,function(a){h?(h(a),h=null):n=a},c);k.calledRun?d():(k.preRun||(k.preRun=[]),k.preRun.push(d))})({files:[{filename:"/nsk.png",start:0,end:939,
audio:0},{filename:"/who.png",start:939,end:1470,audio:0},{filename:"/ball.png",start:1470,end:1752,audio:0},{filename:"/256.png",start:1752,end:7391,audio:0},{filename:"/mplus-1p-medium.ttf",start:7391,end:1753003,audio:0}],remote_package_size:1753003,package_uuid:"7e83b388-411e-4628-b23c-941dc776a2ba"});var aa={},ba;for(ba in k)k.hasOwnProperty(ba)&&(aa[ba]=k[ba]);var ca="./this.program";function da(a,b){throw b;}var ea=!1,m=!1,fa=!1,ha=!1,ia=!1;ea="object"===typeof window;m="function"===typeof importScripts;
fa=(ha="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)&&!ea&&!m;ia=!ea&&!fa&&!m;var ja="",ka,la,ma,na;
if(fa){ja=__dirname+"/";var oa,pa;ka=function(a,b){oa||(oa=require("fs"));pa||(pa=require("path"));a=pa.normalize(a);a=oa.readFileSync(a);return b?a:a.toString()};ma=function(a){a=ka(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);"undefined"!==typeof module&&(module.exports=k);process.on("uncaughtException",function(a){if(!(a instanceof qa))throw a;});process.on("unhandledRejection",p);da=function(a){process.exit(a)};
k.inspect=function(){return"[Emscripten Module object]"}}else if(ia)"undefined"!=typeof read&&(ka=function(a){return read(a)}),ma=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"function"===typeof quit&&(da=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(ea||m)m?
ja=self.location.href:document.currentScript&&(ja=document.currentScript.src),ja=0!==ja.indexOf("blob:")?ja.substr(0,ja.lastIndexOf("/")+1):"",ka=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},m&&(ma=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),la=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||
0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},na=function(a){document.title=a};var ra=k.print||console.log.bind(console),l=k.printErr||console.warn.bind(console);for(ba in aa)aa.hasOwnProperty(ba)&&(k[ba]=aa[ba]);aa=null;k.thisProgram&&(ca=k.thisProgram);k.quit&&(da=k.quit);k.setWindowTitle=na;function sa(a,b){b||(b=16);return Math.ceil(a/b)*b}function ta(a){ua||(ua={});ua[a]||(ua[a]=1,l(a))}var ua;
function va(a,b){b&&b.length?k.dynCall_vi.apply(null,[a].concat(b)):k.dynCall_vi.call(null,a)}var wa=0,xa;k.wasmBinary&&(xa=k.wasmBinary);var ya;k.noExitRuntime&&(ya=k.noExitRuntime);"object"!==typeof WebAssembly&&l("no native wasm support detected");
function za(a,b){var c="float";"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":r[a>>0]=b;break;case "i8":r[a>>0]=b;break;case "i16":Aa[a>>1]=b;break;case "i32":v[a>>2]=b;break;case "i64":w=[b>>>0,(x=b,1<=+Ba(x)?0<x?(Ca(+Da(x/4294967296),4294967295)|0)>>>0:~~+Ea((x-+(~~x>>>0))/4294967296)>>>0:0)];v[a>>2]=w[0];v[a+4>>2]=w[1];break;case "float":y[a>>2]=b;break;case "double":A[a>>3]=b;break;default:p("invalid type for setValue: "+c)}}
var Fa,Ga=new WebAssembly.Table({initial:1542,maximum:1542,element:"anyfunc"}),Ha=!1;function assert(a,b){a||p("Assertion failed: "+b)}function Ia(a){if("number"===typeof a){var b=!0;var c=a}else b=!1,c=a.length;var d=B(Math.max(c,1));if(b){a=d;assert(0==(d&3));for(b=d+(c&-4);a<b;a+=4)v[a>>2]=0;for(b=d+c;a<b;)r[a++>>0]=0;return d}a.subarray||a.slice?C.set(a,d):C.set(new Uint8Array(a),d);return d}var Ja="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Ka(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&Ja)return Ja.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function F(a,b){return a?Ka(C,a,b):""}
function La(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var n=a.charCodeAt(++f);h=65536+((h&1023)<<10)|n&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}function G(a,b,c){return La(a,C,b,c)}
function Na(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function Oa(a){0<a%65536&&(a+=65536-a%65536);return a}var buffer,r,C,Aa,Pa,v,Qa,y,A;
function Ra(a){buffer=a;k.HEAP8=r=new Int8Array(a);k.HEAP16=Aa=new Int16Array(a);k.HEAP32=v=new Int32Array(a);k.HEAPU8=C=new Uint8Array(a);k.HEAPU16=Pa=new Uint16Array(a);k.HEAPU32=Qa=new Uint32Array(a);k.HEAPF32=y=new Float32Array(a);k.HEAPF64=A=new Float64Array(a)}var Sa=k.TOTAL_MEMORY||16777216;k.wasmMemory?Fa=k.wasmMemory:Fa=new WebAssembly.Memory({initial:Sa/65536});Fa&&(buffer=Fa.buffer);Sa=buffer.byteLength;Ra(buffer);v[48824]=5438336;
function Ta(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.jf;"number"===typeof c?void 0===b.qf?k.dynCall_v(c):k.dynCall_vi(c,b.qf):c(void 0===b.qf?null:b.qf)}}}var Ua=[],Va=[],Wa=[],Xa=[],Ya=[],Za=!1;function $a(){var a=k.preRun.shift();Ua.unshift(a)}var Ba=Math.abs,Ea=Math.ceil,Da=Math.floor,Ca=Math.min,ab=0,bb=null,cb=null;function db(){ab++;k.monitorRunDependencies&&k.monitorRunDependencies(ab)}
function eb(){ab--;k.monitorRunDependencies&&k.monitorRunDependencies(ab);if(0==ab&&(null!==bb&&(clearInterval(bb),bb=null),cb)){var a=cb;cb=null;a()}}k.preloadedImages={};k.preloadedAudios={};function p(a){if(k.onAbort)k.onAbort(a);ra(a);l(a);Ha=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}
function fb(){var a=gb;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var gb="index.wasm";if(!fb()){var hb=gb;gb=k.locateFile?k.locateFile(hb,ja):ja+hb}function ib(){try{if(xa)return new Uint8Array(xa);if(ma)return ma(gb);throw"both async and sync fetching of the wasm failed";}catch(a){p(a)}}
function jb(){return xa||!ea&&!m||"function"!==typeof fetch?new Promise(function(a){a(ib())}):fetch(gb,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+gb+"'";return a.arrayBuffer()}).catch(function(){return ib()})}
var x,w,lb=[function(a){a=F(a)+"\n\nAbort/Retry/Ignore/AlwaysIgnore? [ariA] :";a=window.prompt(a,"i");null===a&&(a="i");return Ia(kb(a))},function(a,b,c){k.SDL2||(k.SDL2={});var d=k.SDL2;d.fh!==k.canvas&&(d.bf=k.createContext(k.canvas,!1,!0),d.fh=k.canvas);if(d.Sh!==a||d.qh!==b||d.sh!==d.bf)d.image=d.bf.createImageData(a,b),d.Sh=a,d.qh=b,d.sh=d.bf;a=d.image.data;b=c>>2;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var f=v[b];a[e]=f&255;a[e+1]=
f>>8&255;a[e+2]=f>>16&255;a[e+3]=255;b++;e+=4}else if(d.$h!==a&&(d.gh=new Int32Array(a.buffer),d.hh=new Uint8Array(a.buffer)),a=d.gh,c=a.length,a.set(v.subarray(b,b+c)),a=d.hh,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.bf.putImageData(d.image,0,0);return 0},function(a){k.canvas&&(k.canvas.style.cursor=F(a));return 0},function(){k.canvas&&(k.canvas.style.cursor=
"none")},function(a,b,c,d,e){var f=document.createElement("canvas");f.width=a;f.height=b;var h=f.getContext("2d");a=h.createImageData(a,b);b=a.data;e>>=2;var n=0,t;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(t=b.length;n<t;){var q=v[e];b[n]=q&255;b[n+1]=q>>8&255;b[n+2]=q>>16&255;b[n+3]=q>>24&255;e++;n+=4}else b=new Int32Array(b.buffer),t=b.length,b.set(v.subarray(e,e+t));h.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+
" "+d+", auto";d=B(c.length+1);G(c,d,c.length+1);return d},function(){return screen.width},function(){return screen.height},function(a){"undefined"!==typeof k.setWindowTitle&&k.setWindowTitle(F(a));return 0},function(){return"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?1:0},function(){return"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?1:0},function(a){var b=k.SDL2;
if(a){void 0!==b.capture.Hf&&clearTimeout(b.capture.Hf);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c]);b.capture.stream=void 0}void 0!==b.capture.Ze&&(b.capture.Ze.onaudioprocess=function(){},b.capture.Ze.disconnect(),b.capture.Ze=void 0);void 0!==b.capture.Of&&(b.capture.Of.disconnect(),b.capture.Of=void 0);void 0!==b.capture.Yf&&(b.capture.Yf=void 0);b.capture=void 0}else void 0!=b.audio.Ze&&(b.audio.Ze.disconnect(),
b.audio.Ze=void 0),b.audio=void 0;void 0!==b.We&&void 0===b.audio&&void 0===b.capture&&(b.We.close(),b.We=void 0)},function(a){"undefined"===typeof k.SDL2&&(k.SDL2={});var b=k.SDL2;a?b.capture={}:b.audio={};b.We||("undefined"!==typeof AudioContext?b.We=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.We=new webkitAudioContext));return void 0===b.We?-1:0},function(){return k.SDL2.We.sampleRate},function(a,b,c,d){function e(){}function f(e){void 0!==h.capture.Hf&&(clearTimeout(h.capture.Hf),
h.capture.Hf=void 0);h.capture.Of=h.We.createMediaStreamSource(e);h.capture.Ze=h.We.createScriptProcessor(b,a,1);h.capture.Ze.onaudioprocess=function(a){void 0!==h&&void 0!==h.capture&&(a.outputBuffer.getChannelData(0).fill(0),h.capture.gg=a.inputBuffer,va(c,[d]))};h.capture.Of.connect(h.capture.Ze);h.capture.Ze.connect(h.We.destination);h.capture.stream=e}var h=k.SDL2;h.capture.Yf=h.We.createBuffer(a,b,h.We.sampleRate);h.capture.Yf.getChannelData(0).fill(0);h.capture.Hf=setTimeout(function(){h.capture.gg=
h.capture.Yf;va(c,[d])},b/h.We.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},function(a,b,c,d){var e=k.SDL2;e.audio.Ze=e.We.createScriptProcessor(b,0,a);e.audio.Ze.onaudioprocess=function(a){void 0!==e&&void 0!==e.audio&&(e.audio.Ag=a.outputBuffer,va(c,[d]))};e.audio.Ze.connect(e.We.destination)},
function(a,b){for(var c=k.SDL2,d=c.capture.gg.numberOfChannels,e=0;e<d;++e){var f=c.capture.gg.getChannelData(e);if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";if(1==d)for(var h=0;h<b;++h)za(a+4*h,f[h]);else for(h=0;h<b;++h)za(a+4*(h*d+e),f[h])}},function(a,b){for(var c=k.SDL2,d=c.audio.Ag.numberOfChannels,e=0;e<d;++e){var f=c.audio.Ag.getChannelData(e);if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+
f.length+" samples vs expected "+b+" samples!";for(var h=0;h<b;++h)f[h]=y[a+(h*d+e<<2)>>2]}}],mb=[];Va.push({jf:function(){nb()}});function ob(a){k.___errno_location&&(v[k.___errno_location()>>2]=a)}function qb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}
function rb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=qb(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}function sb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function tb(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function ub(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=qb(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}var vb=[];function wb(a,b){vb[a]={input:[],output:[],xf:b};xb(a,yb)}
var yb={open:function(a){var b=vb[a.node.rdev];if(!b)throw new H(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.xf.flush(a.tty)},flush:function(a){a.tty.xf.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.xf.Eg)throw new H(60);for(var e=0,f=0;f<d;f++){try{var h=a.tty.xf.Eg(a.tty)}catch(n){throw new H(29);}if(void 0===h&&0===e)throw new H(6);if(null===h||void 0===h)break;e++;b[c+f]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.xf.pg)throw new H(60);
try{for(var e=0;e<d;e++)a.tty.xf.pg(a.tty,b[c+e])}catch(f){throw new H(29);}d&&(a.node.timestamp=Date.now());return e}},zb={Eg:function(a){if(!a.input.length){var b=null;if(fa){var c=Buffer.pf?Buffer.pf(256):new Buffer(256),d=0;try{d=oa.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(-1!=e.toString().indexOf("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=kb(b,!0)}return a.input.shift()},pg:function(a,b){null===b||10===b?(ra(Ka(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(ra(Ka(a.output,0)),a.output=[])}},Ab={pg:function(a,b){null===b||10===b?(l(Ka(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(l(Ka(a.output,0)),a.output=[])}},I={gf:null,kf:function(){return I.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new H(63);I.gf||(I.gf={dir:{node:{mf:I.Te.mf,af:I.Te.af,lookup:I.Te.lookup,Pf:I.Te.Pf,rename:I.Te.rename,unlink:I.Te.unlink,rmdir:I.Te.rmdir,readdir:I.Te.readdir,symlink:I.Te.symlink},stream:{rf:I.Ue.rf}},file:{node:{mf:I.Te.mf,af:I.Te.af},stream:{rf:I.Ue.rf,read:I.Ue.read,write:I.Ue.write,vg:I.Ue.vg,Lg:I.Ue.Lg,Wf:I.Ue.Wf}},link:{node:{mf:I.Te.mf,af:I.Te.af,readlink:I.Te.readlink},stream:{}},zg:{node:{mf:I.Te.mf,
af:I.Te.af},stream:Bb}});c=Cb(a,b,c,d);16384===(c.mode&61440)?(c.Te=I.gf.dir.node,c.Ue=I.gf.dir.stream,c.Se={}):32768===(c.mode&61440)?(c.Te=I.gf.file.node,c.Ue=I.gf.file.stream,c.Ve=0,c.Se=null):40960===(c.mode&61440)?(c.Te=I.gf.link.node,c.Ue=I.gf.link.stream):8192===(c.mode&61440)&&(c.Te=I.gf.zg.node,c.Ue=I.gf.zg.stream);c.timestamp=Date.now();a&&(a.Se[b]=c);return c},di:function(a){if(a.Se&&a.Se.subarray){for(var b=[],c=0;c<a.Ve;++c)b.push(a.Se[c]);return b}return a.Se},ei:function(a){return a.Se?
a.Se.subarray?a.Se.subarray(0,a.Ve):new Uint8Array(a.Se):new Uint8Array},Bg:function(a,b){var c=a.Se?a.Se.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.Se,a.Se=new Uint8Array(b),0<a.Ve&&a.Se.set(c.subarray(0,a.Ve),0))},Ah:function(a,b){if(a.Ve!=b)if(0==b)a.Se=null,a.Ve=0;else{if(!a.Se||a.Se.subarray){var c=a.Se;a.Se=new Uint8Array(new ArrayBuffer(b));c&&a.Se.set(c.subarray(0,Math.min(b,a.Ve)))}else if(a.Se||(a.Se=[]),a.Se.length>b)a.Se.length=b;else for(;a.Se.length<
b;)a.Se.push(0);a.Ve=b}},Te:{mf:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.Ve:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.dh=4096;b.blocks=Math.ceil(b.size/b.dh);return b},af:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=
b.timestamp);void 0!==b.size&&I.Ah(a,b.size)},lookup:function(){throw Db[44];},Pf:function(a,b,c,d){return I.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=Eb(b,c)}catch(f){}if(d)for(var e in d.Se)throw new H(55);}delete a.parent.Se[a.name];a.name=c;b.Se[c]=a;a.parent=b},unlink:function(a,b){delete a.Se[b]},rmdir:function(a,b){var c=Eb(a,b),d;for(d in c.Se)throw new H(55);delete a.Se[b]},readdir:function(a){var b=[".",".."],c;for(c in a.Se)a.Se.hasOwnProperty(c)&&
b.push(c);return b},symlink:function(a,b,c){a=I.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new H(28);return a.link}},Ue:{read:function(a,b,c,d,e){var f=a.node.Se;if(e>=a.node.Ve)return 0;a=Math.min(a.node.Ve-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){f=!1;if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Se||a.Se.subarray)){if(f)return a.Se=b.subarray(c,
c+d),a.Ve=d;if(0===a.Ve&&0===e)return a.Se=new Uint8Array(b.subarray(c,c+d)),a.Ve=d;if(e+d<=a.Ve)return a.Se.set(b.subarray(c,c+d),e),d}I.Bg(a,e+d);if(a.Se.subarray&&b.subarray)a.Se.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.Se[e+f]=b[c+f];a.Ve=Math.max(a.Ve,e+d);return d},rf:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Ve);if(0>b)throw new H(28);return b},vg:function(a,b,c){I.Bg(a.node,b+c);a.node.Ve=Math.max(a.node.Ve,b+c)},Lg:function(a,b,c,d,e,f,h){if(32768!==
(a.node.mode&61440))throw new H(43);c=a.node.Se;if(h&2||c.buffer!==b&&c.buffer!==b.buffer){if(0<e||e+d<a.node.Ve)c.subarray?c=c.subarray(e,e+d):c=Array.prototype.slice.call(c,e,e+d);a=!0;e=b.buffer==r.buffer;d=B(d);if(!d)throw new H(48);(e?r:b).set(c,d)}else a=!1,d=c.byteOffset;return{oi:d,ah:a}},Wf:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new H(43);if(e&2)return 0;I.Ue.write(a,b,0,d,c,!1);return 0}}},Fb=null,Gb={},Hb=[],Ib=1,Jb=null,Kb=!0,Lb={},H=null,Db={};
function Mb(a,b){a=ub("/",a);b=b||{};if(!a)return{path:"",node:null};var c={Cg:!0,qg:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.qg)throw new H(32);a=qb(a.split("/").filter(function(a){return!!a}),!1);var e=Fb;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=Eb(e,a[d]);c=rb(c+"/"+a[d]);e.Ff&&(!f||f&&b.Cg)&&(e=e.Ff.root);if(!f||b.jg)for(f=0;40960===(e.mode&61440);)if(e=Nb(c),c=ub(sb(c),e),e=Mb(c,{qg:b.qg}).node,40<f++)throw new H(32);}return{path:c,node:e}}
function Ob(a){for(var b;;){if(a===a.parent)return a=a.kf.Ng,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Pb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Jb.length}function Qb(a){var b=Pb(a.parent.id,a.name);a.vf=Jb[b];Jb[b]=a}function Eb(a,b){var c;if(c=(c=Rb(a,"x"))?c:a.Te.lookup?0:2)throw new H(c,a);for(c=Jb[Pb(a.id,b)];c;c=c.vf){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Te.lookup(a,b)}
function Cb(a,b,c,d){Sb||(Sb=function(a,b,c,d){a||(a=this);this.parent=a;this.kf=a.kf;this.Ff=null;this.id=Ib++;this.name=b;this.mode=c;this.Te={};this.Ue={};this.rdev=d},Sb.prototype={},Object.defineProperties(Sb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},xh:{get:function(){return 16384===(this.mode&61440)}},wh:{get:function(){return 8192===
(this.mode&61440)}}}));a=new Sb(a,b,c,d);Qb(a);return a}var Tb={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Ub(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Rb(a,b){if(Kb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}function Vb(a,b){try{return Eb(a,b),20}catch(c){}return Rb(a,"wx")}
function Wb(a){var b=4096;for(a=a||0;a<=b;a++)if(!Hb[a])return a;throw new H(33);}function Xb(a,b){Yb||(Yb=function(){},Yb.prototype={},Object.defineProperties(Yb.prototype,{object:{get:function(){return this.node},set:function(a){this.node=a}}}));var c=new Yb,d;for(d in a)c[d]=a[d];a=c;b=Wb(b);a.fd=b;return Hb[b]=a}var Bb={open:function(a){a.Ue=Gb[a.node.rdev].Ue;a.Ue.open&&a.Ue.open(a)},rf:function(){throw new H(70);}};function xb(a,b){Gb[a]={Ue:b}}
function Zb(a,b){var c="/"===b,d=!b;if(c&&Fb)throw new H(10);if(!c&&!d){var e=Mb(b,{Cg:!1});b=e.path;e=e.node;if(e.Ff)throw new H(10);if(16384!==(e.mode&61440))throw new H(54);}b={type:a,mi:{},Ng:b,yh:[]};a=a.kf(b);a.kf=b;b.root=a;c?Fb=a:e&&(e.Ff=b,e.kf&&e.kf.yh.push(b))}function $b(a,b,c){var d=Mb(a,{parent:!0}).node;a=tb(a);if(!a||"."===a||".."===a)throw new H(28);var e=Vb(d,a);if(e)throw new H(e);if(!d.Te.Pf)throw new H(63);return d.Te.Pf(d,a,b,c)}
function K(a,b){return $b(a,(void 0!==b?b:511)&1023|16384,0)}function ac(a,b,c){"undefined"===typeof c&&(c=b,b=438);return $b(a,b|8192,c)}function bc(a,b){if(!ub(a))throw new H(44);var c=Mb(b,{parent:!0}).node;if(!c)throw new H(44);b=tb(b);var d=Vb(c,b);if(d)throw new H(d);if(!c.Te.symlink)throw new H(63);return c.Te.symlink(c,b,a)}
function cc(a){var b=Mb(a,{parent:!0}).node,c=tb(a),d=Eb(b,c);a:{try{var e=Eb(b,c)}catch(h){e=h.hf;break a}var f=Rb(b,"wx");e=f?f:16384===(e.mode&61440)?31:0}if(e)throw new H(e);if(!b.Te.unlink)throw new H(63);if(d.Ff)throw new H(10);try{Lb.willDeletePath&&Lb.willDeletePath(a)}catch(h){console.log("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+h.message)}b.Te.unlink(b,c);b=Pb(d.parent.id,d.name);if(Jb[b]===d)Jb[b]=d.vf;else for(b=Jb[b];b;){if(b.vf===d){b.vf=d.vf;break}b=b.vf}try{if(Lb.onDeletePath)Lb.onDeletePath(a)}catch(h){console.log("FS.trackingDelegate['onDeletePath']('"+
a+"') threw an exception: "+h.message)}}function Nb(a){a=Mb(a).node;if(!a)throw new H(44);if(!a.Te.readlink)throw new H(28);return ub(Ob(a.parent),a.Te.readlink(a))}function dc(a,b){var c;"string"===typeof a?c=Mb(a,{jg:!0}).node:c=a;if(!c.Te.af)throw new H(63);c.Te.af(c,{mode:b&4095|c.mode&-4096,timestamp:Date.now()})}
function ec(a,b,c,d){if(""===a)throw new H(44);if("string"===typeof b){var e=Tb[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=rb(a);try{f=Mb(a,{jg:!(b&131072)}).node}catch(n){}}e=!1;if(b&64)if(f){if(b&128)throw new H(20);}else f=$b(a,c,0),e=!0;if(!f)throw new H(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&16384!==(f.mode&61440))throw new H(54);if(!e&&(c=f?40960===(f.mode&61440)?
32:16384===(f.mode&61440)&&("r"!==Ub(b)||b&512)?31:Rb(f,Ub(b)):44))throw new H(c);if(b&512){c=f;var h;"string"===typeof c?h=Mb(c,{jg:!0}).node:h=c;if(!h.Te.af)throw new H(63);if(16384===(h.mode&61440))throw new H(31);if(32768!==(h.mode&61440))throw new H(28);if(c=Rb(h,"w"))throw new H(c);h.Te.af(h,{size:0,timestamp:Date.now()})}b&=-641;d=Xb({node:f,path:Ob(f),flags:b,seekable:!0,position:0,Ue:f.Ue,Ph:[],error:!1},d);d.Ue.open&&d.Ue.open(d);!k.logReadFiles||b&1||(fc||(fc={}),a in fc||(fc[a]=1,console.log("FS.trackingDelegate error on read file: "+
a)));try{Lb.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=1),0!==(b&2097155)&&(f|=2),Lb.onOpenFile(a,f))}catch(n){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+n.message)}return d}function hc(a){if(null===a.fd)throw new H(8);a.lg&&(a.lg=null);try{a.Ue.close&&a.Ue.close(a)}catch(b){throw b;}finally{Hb[a.fd]=null}a.fd=null}
function ic(a,b,c){if(null===a.fd)throw new H(8);if(!a.seekable||!a.Ue.rf)throw new H(70);if(0!=c&&1!=c&&2!=c)throw new H(28);a.position=a.Ue.rf(a,b,c);a.Ph=[]}
function jc(a,b,c,d,e,f){if(0>d||0>e)throw new H(28);if(null===a.fd)throw new H(8);if(0===(a.flags&2097155))throw new H(8);if(16384===(a.node.mode&61440))throw new H(31);if(!a.Ue.write)throw new H(28);a.flags&1024&&ic(a,0,2);var h="undefined"!==typeof e;if(!h)e=a.position;else if(!a.seekable)throw new H(70);b=a.Ue.write(a,b,c,d,e,f);h||(a.position+=b);try{if(a.path&&Lb.onWriteToFile)Lb.onWriteToFile(a.path)}catch(n){console.log("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+
n.message)}return b}function kc(){H||(H=function(a,b){this.node=b;this.Gh=function(a){this.hf=a};this.Gh(a);this.message="FS error"},H.prototype=Error(),H.prototype.constructor=H,[44].forEach(function(a){Db[a]=new H(a);Db[a].stack="<generic error, no stack>"}))}var lc;function mc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function nc(a,b,c,d){a=rb(("string"===typeof a?a:Ob(a))+"/"+b);return K(a,mc(c,d))}
function oc(a,b){a="string"===typeof a?a:Ob(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=rb(a+"/"+c);try{K(d)}catch(e){}a=d}}return d}function pc(a,b,c,d){a=rb(("string"===typeof a?a:Ob(a))+"/"+b);c=mc(c,d);return $b(a,(void 0!==c?c:438)&4095|32768,0)}
function qc(a,b,c,d,e,f){a=b?rb(("string"===typeof a?a:Ob(a))+"/"+b):a;d=mc(d,e);e=$b(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var h=c.length;b<h;++b)a[b]=c.charCodeAt(b);c=a}dc(e,d|146);a=ec(e,"w");jc(a,c,0,c.length,0,f);hc(a);dc(e,d)}return e}
function rc(a,b,c,d){a=rb(("string"===typeof a?a:Ob(a))+"/"+b);b=mc(!!c,!!d);rc.Jg||(rc.Jg=64);var e=rc.Jg++<<8|0;xb(e,{open:function(a){a.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(a,b,d,e){for(var f=0,h=0;h<e;h++){try{var n=c()}catch(J){throw new H(29);}if(void 0===n&&0===f)throw new H(6);if(null===n||void 0===n)break;f++;b[d+h]=n}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,e){for(var f=0;f<e;f++)try{d(b[c+f])}catch(u){throw new H(29);}e&&
(a.node.timestamp=Date.now());return f}});return ac(a,b,e)}function sc(a,b,c){a=rb(("string"===typeof a?a:Ob(a))+"/"+b);return bc(c,a)}
function tc(a){if(a.wh||a.xh||a.link||a.Se)return!0;var b=!0;if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ka)try{a.Se=kb(ka(a.url),!0),a.Ve=a.Se.length}catch(c){b=!1}else throw Error("Cannot load without read() or XMLHttpRequest.");b||ob(29);return b}
function uc(a,b,c,d,e){function f(){this.mg=!1;this.Lf=[]}f.prototype.get=function(a){if(!(a>this.length-1||0>a)){var b=a%this.chunkSize;return this.Fg(a/this.chunkSize|0)[b]}};f.prototype.Fh=function(a){this.Fg=a};f.prototype.xg=function(){var a=new XMLHttpRequest;a.open("HEAD",c,!1);a.send(null);if(!(200<=a.status&&300>a.status||304===a.status))throw Error("Couldn't load "+c+". Status: "+a.status);var b=Number(a.getResponseHeader("Content-length")),d,e=(d=a.getResponseHeader("Accept-Ranges"))&&
"bytes"===d;a=(d=a.getResponseHeader("Content-Encoding"))&&"gzip"===d;var f=1048576;e||(f=b);var h=this;h.Fh(function(a){var d=a*f,e=(a+1)*f-1;e=Math.min(e,b-1);if("undefined"===typeof h.Lf[a]){var n=h.Lf;if(d>e)throw Error("invalid range ("+d+", "+e+") or no bytes requested!");if(e>b-1)throw Error("only "+b+" bytes available! programmer error!");var z=new XMLHttpRequest;z.open("GET",c,!1);b!==f&&z.setRequestHeader("Range","bytes="+d+"-"+e);"undefined"!=typeof Uint8Array&&(z.responseType="arraybuffer");
z.overrideMimeType&&z.overrideMimeType("text/plain; charset=x-user-defined");z.send(null);if(!(200<=z.status&&300>z.status||304===z.status))throw Error("Couldn't load "+c+". Status: "+z.status);d=void 0!==z.response?new Uint8Array(z.response||[]):kb(z.responseText||"",!0);n[a]=d}if("undefined"===typeof h.Lf[a])throw Error("doXHR failed!");return h.Lf[a]});if(a||!b)f=b=1,f=b=this.Fg(0).length,console.log("LazyFiles on gzip forces download of the whole file when length is accessed");this.$g=b;this.Zg=
f;this.mg=!0};if("undefined"!==typeof XMLHttpRequest){if(!m)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var h=new f;Object.defineProperties(h,{length:{get:function(){this.mg||this.xg();return this.$g}},chunkSize:{get:function(){this.mg||this.xg();return this.Zg}}});var n=void 0}else n=c,h=void 0;var t=pc(a,b,d,e);h?t.Se=h:n&&(t.Se=null,t.url=n);Object.defineProperties(t,{Ve:{get:function(){return this.Se.length}}});var q=
{};Object.keys(t.Ue).forEach(function(a){var b=t.Ue[a];q[a]=function(){if(!tc(t))throw new H(29);return b.apply(null,arguments)}});q.read=function(a,b,c,d,e){if(!tc(t))throw new H(29);a=a.node.Se;if(e>=a.length)return 0;d=Math.min(a.length-e,d);if(a.slice)for(var f=0;f<d;f++)b[c+f]=a[e+f];else for(f=0;f<d;f++)b[c+f]=a.get(e+f);return d};t.Ue=q;return t}
function vc(a,b,c,d,e,f,h,n,t,q){function u(c){function z(c){q&&q();n||qc(a,b,c,d,e,t);f&&f();eb(J)}var u=!1;k.preloadPlugins.forEach(function(a){!u&&a.canHandle(D)&&(a.handle(c,D,z,function(){h&&h();eb(J)}),u=!0)});u||z(c)}g.Hg();var D=b?ub(rb(a+"/"+b)):a,J="cp "+D;db(J);"string"==typeof c?g.bh(c,function(a){u(a)},h):u(c)}var wc={},Sb,Yb,fc,xc={},yc=0;function L(){yc+=4;return v[yc-4>>2]}function zc(a){void 0===a&&(a=L());a=Hb[a];if(!a)throw new H(8);return a}function Ac(){p()}
function Bc(){p("To use dlopen, you need to use Emscripten's linking support, see https://github.com/emscripten-core/emscripten/wiki/Linking")}
function Cc(a,b){g.Re.Zf=a;g.Re.$f=b;if(g.Re.jf)if(0==a)g.Re.nf=function(){var a=Math.max(0,g.Re.Kh+b-Ac())|0;setTimeout(g.Re.Xf,a)},g.Re.method="timeout";else if(1==a)g.Re.nf=function(){g.requestAnimationFrame(g.Re.Xf)},g.Re.method="rAF";else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(a){if("setimmediate"===a.data||"setimmediate"===a.data.target)a.stopPropagation(),c.shift()()},!0);setImmediate=function(a){c.push(a);m?(void 0===k.setImmediates&&(k.setImmediates=
[]),k.setImmediates.push(a),postMessage({target:"setimmediate"})):postMessage("setimmediate","*")}}g.Re.nf=function(){setImmediate(g.Re.Xf)};g.Re.method="immediate"}}
function Dc(a,b,c,d,e){ya=!0;assert(!g.Re.jf,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");g.Re.jf=a;g.Re.qf=d;var f="undefined"!==typeof d?function(){k.dynCall_vi(a,d)}:function(){k.dynCall_v(a)};var h=g.Re.tf;g.Re.Xf=function(){if(!Ha)if(0<g.Re.Tg.length){var a=Date.now(),b=g.Re.Tg.shift();b.jf(b.qf);if(g.Re.rg){var c=g.Re.rg,d=0==c%1?c-1:Math.floor(c);
g.Re.rg=b.Zh?d:(8*c+(d+.5))/9}console.log('main loop blocker "'+b.name+'" took '+(Date.now()-a)+" ms");g.Re.Qh();h<g.Re.tf||setTimeout(g.Re.Xf,0)}else h<g.Re.tf||(g.Re.hg=g.Re.hg+1|0,1==g.Re.Zf&&1<g.Re.$f&&0!=g.Re.hg%g.Re.$f?g.Re.nf():(0==g.Re.Zf&&(g.Re.Kh=Ac()),"timeout"===g.Re.method&&k.bf&&(l("Looks like you are rendering without using requestAnimationFrame for the main loop. You should use 0 for the frame rate in emscripten_set_main_loop in order to use requestAnimationFrame, as that can greatly improve your frame rates!"),
g.Re.method=""),g.Re.Ch(f),h<g.Re.tf||g.Re.nf()))};e||(b&&0<b?Cc(0,1E3/b):Cc(1,1),g.Re.nf());if(c)throw"SimulateInfiniteLoop";}
g={Re:{nf:null,method:"",tf:0,jf:null,qf:0,Zf:0,$f:0,hg:0,Tg:[],pause:function(){g.Re.nf=null;g.Re.tf++},resume:function(){g.Re.tf++;var a=g.Re.Zf,b=g.Re.$f,c=g.Re.jf;g.Re.jf=null;Dc(c,0,!1,g.Re.qf,!0);Cc(a,b);g.Re.nf()},Qh:function(){if(k.setStatus){var a=k.statusMessage||"Please wait...",b=g.Re.rg,c=g.Re.bi;b?b<c?k.setStatus(a+" ("+(c-b)+"/"+c+")"):k.setStatus(a):k.setStatus("")}},Ch:function(a){if(!(Ha||k.preMainLoop&&!1===k.preMainLoop())){try{a()}catch(b){if(b instanceof qa)return;b&&"object"===
typeof b&&b.stack&&l("exception thrown: "+[b,b.stack]);throw b;}k.postMainLoop&&k.postMainLoop()}}},Cf:!1,og:!1,Mg:[],workers:[],Hg:function(){function a(){g.og=document.pointerLockElement===k.canvas||document.mozPointerLockElement===k.canvas||document.webkitPointerLockElement===k.canvas||document.msPointerLockElement===k.canvas}k.preloadPlugins||(k.preloadPlugins=[]);if(!g.uh){g.uh=!0;try{g.Mf=!0}catch(c){g.Mf=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}g.BlobBuilder=
"undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:g.Mf?null:console.log("warning: no BlobBuilder");g.Kf="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;k.Qg||"undefined"!==typeof g.Kf||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),k.Qg=!0);k.preloadPlugins.push({canHandle:function(a){return!k.Qg&&/\.(jpg|jpeg|png|bmp)$/i.test(a)},handle:function(a,
b,e,f){var c=null;if(g.Mf)try{c=new Blob([a],{type:g.kg(b)}),c.size!==a.length&&(c=new Blob([(new Uint8Array(a)).buffer],{type:g.kg(b)}))}catch(q){ta("Blob constructor present but fails: "+q+"; falling back to blob builder")}c||(c=new g.BlobBuilder,c.append((new Uint8Array(a)).buffer),c=c.getBlob());var d=g.Kf.createObjectURL(c),t=new Image;t.onload=function(){assert(t.complete,"Image "+b+" could not be decoded");var c=document.createElement("canvas");c.width=t.width;c.height=t.height;c.getContext("2d").drawImage(t,
0,0);k.preloadedImages[b]=c;g.Kf.revokeObjectURL(d);e&&e(a)};t.onerror=function(){console.log("Image "+d+" could not be decoded");f&&f()};t.src=d}});k.preloadPlugins.push({canHandle:function(a){return!k.li&&a.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(a,b,e,f){function c(c){t||(t=!0,k.preloadedAudios[b]=c,e&&e(a))}function d(){t||(t=!0,k.preloadedAudios[b]=new Audio,f&&f())}var t=!1;if(g.Mf){try{var q=new Blob([a],{type:g.kg(b)})}catch(D){return d()}q=g.Kf.createObjectURL(q);var u=
new Audio;u.addEventListener("canplaythrough",function(){c(u)},!1);u.onerror=function(){if(!t){console.log("warning: browser could not fully decode audio "+b+", trying slower base64 approach");for(var d="",e=0,f=0,h=0;h<a.length;h++)for(e=e<<8|a[h],f+=8;6<=f;){var n=e>>f-6&63;f-=6;d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[n]}2==f?(d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(e&3)<<4],d+="=="):4==f&&(d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(e&
15)<<2],d+="=");u.src="data:audio/x-"+b.substr(-3)+";base64,"+d;c(u)}};u.src=q;g.Dh(function(){c(u)},1E4)}else return d()}});var b=k.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",
a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),k.elementPointerLock&&b.addEventListener("click",function(a){!g.og&&k.canvas.requestPointerLock&&(k.canvas.requestPointerLock(),a.preventDefault())},!1))}},createContext:function(a,b,c,d){if(b&&k.bf&&a==k.canvas)return k.bf;var e;if(b){var f={antialias:!1,alpha:!1,Kg:1};if(d)for(var h in d)f[h]=d[h];if("undefined"!==typeof Ec&&
(e=Fc(a,f)))var n=Gc[e].lf}else n=a.getContext("2d");if(!n)return null;c&&(b||assert("undefined"===typeof M,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),k.bf=n,b&&Hc(e),k.Rh=b,g.Mg.forEach(function(a){a()}),g.Hg());return n},ai:function(){},Dg:!1,Nf:void 0,yf:void 0,requestFullscreen:function(a,b,c){function d(){g.Cf=!1;var a=e.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||
document.webkitCurrentFullScreenElement)===a?(e.exitFullscreen=g.exitFullscreen,g.Nf&&e.requestPointerLock(),g.Cf=!0,g.yf?g.Hh():g.Jf(e)):(a.parentNode.insertBefore(e,a),a.parentNode.removeChild(a),g.yf?g.Ih():g.Jf(e));if(k.onFullScreen)k.onFullScreen(g.Cf);if(k.onFullscreen)k.onFullscreen(g.Cf)}g.Nf=a;g.yf=b;g.Wg=c;"undefined"===typeof g.Nf&&(g.Nf=!0);"undefined"===typeof g.yf&&(g.yf=!1);"undefined"===typeof g.Wg&&(g.Wg=null);var e=k.canvas;g.Dg||(g.Dg=!0,document.addEventListener("fullscreenchange",
d,!1),document.addEventListener("mozfullscreenchange",d,!1),document.addEventListener("webkitfullscreenchange",d,!1),document.addEventListener("MSFullscreenChange",d,!1));var f=document.createElement("div");e.parentNode.insertBefore(f,e);f.appendChild(e);f.requestFullscreen=f.requestFullscreen||f.mozRequestFullScreen||f.msRequestFullscreen||(f.webkitRequestFullscreen?function(){f.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(f.webkitRequestFullScreen?function(){f.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:
null);c?f.requestFullscreen({xi:c}):f.requestFullscreen()},Ug:function(a,b,c){l("Browser.requestFullScreen() is deprecated. Please call Browser.requestFullscreen instead.");g.Ug=function(a,b,c){return g.requestFullscreen(a,b,c)};return g.requestFullscreen(a,b,c)},exitFullscreen:function(){if(!g.Cf)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0},wf:0,lh:function(a){var b=
Date.now();if(0===g.wf)g.wf=b+1E3/60;else for(;b+2>=g.wf;)g.wf+=1E3/60;setTimeout(a,Math.max(g.wf-b,0))},requestAnimationFrame:function(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=g.lh;b(a)}},si:function(a){return function(){if(!Ha)return a.apply(null,arguments)}},Bf:!0,Gf:[],ni:function(){g.Bf=!1},ri:function(){g.Bf=!0;if(0<g.Gf.length){var a=g.Gf;g.Gf=[];a.forEach(function(a){a()})}},ti:function(a){return g.requestAnimationFrame(function(){Ha||(g.Bf?a():g.Gf.push(a))})},
Dh:function(a,b){ya=!0;return setTimeout(function(){Ha||(g.Bf?a():g.Gf.push(a))},b)},ui:function(a,b){ya=!0;return setInterval(function(){Ha||g.Bf&&a()},b)},kg:function(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]},getUserMedia:function(a){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)},oh:function(a){return a.movementX||
a.mozMovementX||a.webkitMovementX||0},ph:function(a){return a.movementY||a.mozMovementY||a.webkitMovementY||0},fi:function(a){switch(a.type){case "DOMMouseScroll":var b=a.detail/3;break;case "mousewheel":b=a.wheelDelta/120;break;case "wheel":b=a.deltaY;switch(a.deltaMode){case 0:b/=100;break;case 1:b/=3;break;case 2:b*=80;break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}return b},Sf:0,Tf:0,Qf:0,Rf:0,touches:{},Ig:{},
Xh:function(a){if(g.og)"mousemove"!=a.type&&"mozMovementX"in a?g.Qf=g.Rf=0:(g.Qf=g.oh(a),g.Rf=g.ph(a)),g.Sf+=g.Qf,g.Tf+=g.Rf;else{var b=k.canvas.getBoundingClientRect(),c=k.canvas.width,d=k.canvas.height,e="undefined"!==typeof window.scrollX?window.scrollX:window.pageXOffset,f="undefined"!==typeof window.scrollY?window.scrollY:window.pageYOffset;if("touchstart"===a.type||"touchend"===a.type||"touchmove"===a.type){var h=a.wi;if(void 0!==h)if(e=h.pageX-(e+b.left),f=h.pageY-(f+b.top),e*=c/b.width,f*=
d/b.height,b={x:e,y:f},"touchstart"===a.type)g.Ig[h.identifier]=b,g.touches[h.identifier]=b;else if("touchend"===a.type||"touchmove"===a.type)(a=g.touches[h.identifier])||(a=b),g.Ig[h.identifier]=a,g.touches[h.identifier]=b}else h=a.pageX-(e+b.left),a=a.pageY-(f+b.top),h*=c/b.width,a*=d/b.height,g.Qf=h-g.Sf,g.Rf=a-g.Tf,g.Sf=h,g.Tf=a}},bh:function(a,b,c,d){var e=d?"":"al "+a;la(a,function(c){assert(c,'Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(c));e&&eb(e)},function(){if(c)c();
else throw'Loading data file "'+a+'" failed.';});e&&db(e)},Bh:[],ug:function(){var a=k.canvas;g.Bh.forEach(function(b){b(a.width,a.height)})},Eh:function(a,b,c){g.Jf(k.canvas,a,b);c||g.ug()},Ai:0,zi:0,Hh:function(){g.Jf(k.canvas);g.ug()},Ih:function(){g.Jf(k.canvas);g.ug()},Jf:function(a,b,c){b&&c?(a.Th=b,a.rh=c):(b=a.Th,c=a.rh);var d=b,e=c;k.forcedAspectRatio&&0<k.forcedAspectRatio&&(d/e<k.forcedAspectRatio?d=Math.round(e*k.forcedAspectRatio):e=Math.round(d/k.forcedAspectRatio));if((document.fullscreenElement||
document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*f)}g.yf?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||
e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))},yi:{},Pg:0,gi:function(){var a=g.Pg;g.Pg++;return a}};var N=12288,Ic=!1,Jc=0,Kc=0,Lc=0,O={alpha:!1,depth:!1,stencil:!1,antialias:!1},Mc={},Nc,Oc=1,Pc=0,Qc=[],P=[],Rc=[],Sc=[],Tc=[],Q=[],R=[],Uc=[],Gc={},Vc=null,Wc={},S=[],Xc={},Yc={},Zc=4;function T(a){Pc||(Pc=a)}
function $c(a){for(var b=Oc++,c=a.length;c<b;c++)a[c]=null;return b}var ad=null,bd=[0];function Fc(a,b){if(a=a.getContext("webgl",b)||a.getContext("experimental-webgl",b)){var c=B(8),d={handle:c,attributes:b,version:b.Kg,lf:a};a.canvas&&(a.canvas.Af=d);Gc[c]=d;("undefined"===typeof b.jh||b.jh)&&cd(d);b=c}else b=0;return b}function Hc(a){Vc=Gc[a];k.bf=M=Vc&&Vc.lf}
function dd(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(a,d){b.vertexAttribDivisorANGLE(a,d)},a.drawArraysInstanced=function(a,d,e,f){b.drawArraysInstancedANGLE(a,d,e,f)},a.drawElementsInstanced=function(a,d,e,f,h){b.drawElementsInstancedANGLE(a,d,e,f,h)})}
function ed(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(a){b.deleteVertexArrayOES(a)},a.bindVertexArray=function(a){b.bindVertexArrayOES(a)},a.isVertexArray=function(a){return b.isVertexArrayOES(a)})}function fd(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(a,d){b.drawBuffersWEBGL(a,d)})}
function cd(a){a||(a=Vc);if(!a.th){a.th=!0;var b=a.lf;2>a.version&&(dd(b),ed(b),fd(b));b.cf=b.getExtension("EXT_disjoint_timer_query");var c="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2".split(" ");
(b.getSupportedExtensions()||[]).forEach(function(a){-1!=c.indexOf(a)&&b.getExtension(a)})}}var Ec={},gd,hd;function id(){N=12288;return 1}var jd=0,kd=0,ld=0,md=0,nd=0,od=0,pd=0,qd=0,rd=0,sd=null,td=null,ud=null,vd=!1;function wd(){for(var a=xd.length-1;0<=a;--a)yd(a);xd=[];U=[]}var U=[];
function zd(a,b,c){function d(a,b){if(a.length!=b.length)return!1;for(var c in a)if(a[c]!=b[c])return!1;return!0}for(var e in U){var f=U[e];if(f.tg==a&&d(f.wg,c))return}U.push({tg:a,Rg:b,wg:c});U.sort(function(a,b){return a.Rg<b.Rg})}function Ad(a){for(var b=0;b<U.length;++b)U[b].tg==a&&(U.splice(b,1),--b)}function Bd(){if(Cd&&Dd.Xe)for(var a=0;a<U.length;++a){var b=U[a];U.splice(a,1);--a;b.tg.apply(this,b.wg)}}var Cd=0,Dd=null,xd=[];
function Ed(){return-1!==navigator.userAgent.indexOf("MSIE")||0<navigator.appVersion.indexOf("Trident/")}function yd(a){var b=xd[a];b.target.removeEventListener(b.Ye,b.kh,b.df);xd.splice(a,1)}function Fd(a){function b(b){++Cd;Dd=a;Bd();a.ff(b);Bd();--Cd}if(a.ef)a.kh=b,a.target.addEventListener(a.Ye,b,a.df),xd.push(a),vd||(Xa.push(wd),vd=!0);else for(var c=0;c<xd.length;++c)xd[c].target==a.target&&xd[c].Ye==a.Ye&&yd(c--)}
function Gd(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}function Hd(){return document.fullscreenEnabled||document.mozFullScreenEnabled||document.webkitFullscreenEnabled||document.msFullscreenEnabled}var Id={},Jd,Kd,Ld={},Md=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];
function V(a){try{if(!a)return window;"number"===typeof a&&(a=Md[a]||F(a));return"#window"===a?window:"#document"===a?document:"#screen"===a?screen:"#canvas"===a?k.canvas:"string"===typeof a?document.getElementById(a):a}catch(b){return null}}function Nd(a){"number"===typeof a&&(a=F(a));return a&&"#canvas"!==a?"undefined"!==typeof Ec&&Wc[a]?Wc[a]:V(a):"undefined"!==typeof Ec&&Wc.canvas?Wc.canvas:k.canvas}
function Od(a){var b=W(),c=Pd(8),d=c+4,e=Pd(a.id.length+1);G(a.id,e,a.id.length+1);if(a=Nd(e))v[c>>2]=a.width,v[d>>2]=a.height;c=[v[c>>2],v[d>>2]];X(b);return c}function Qd(a,b,c){a=Nd(a);if(!a)return-4;a.width=b;a.height=c;return 0}function Rd(a,b,c){if(a.Yh){var d=W(),e=Pd(a.id.length+1);G(a.id,e,a.id.length+1);Qd(e,b,c);X(d)}else a.width=b,a.height=c}
function Sd(a){function b(){document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("mozfullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),document.removeEventListener("MSFullscreenChange",b),Rd(a,d,e),a.style.width=f,a.style.height=h,a.style.backgroundColor=n,t||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=
t,a.style.paddingLeft=q,a.style.paddingRight=u,a.style.paddingTop=D,a.style.paddingBottom=J,a.style.marginLeft=z,a.style.marginRight=E,a.style.marginTop=pb,a.style.marginBottom=Ma,document.body.style.margin=ye,document.documentElement.style.overflow=ze,document.body.scroll=Ae,a.style.Gg=Be,a.Af&&a.Af.lf.viewport(0,0,d,e),Ld.sf&&Y(Ld.sf,37,0,Ld.eg))}var c=Od(a),d=c[0],e=c[1],f=a.style.width,h=a.style.height,n=a.style.backgroundColor,t=document.body.style.backgroundColor,q=a.style.paddingLeft,u=a.style.paddingRight,
D=a.style.paddingTop,J=a.style.paddingBottom,z=a.style.marginLeft,E=a.style.marginRight,pb=a.style.marginTop,Ma=a.style.marginBottom,ye=document.body.style.margin,ze=document.documentElement.style.overflow,Ae=document.body.scroll,Be=a.style.Gg;document.addEventListener("fullscreenchange",b);document.addEventListener("mozfullscreenchange",b);document.addEventListener("webkitfullscreenchange",b);document.addEventListener("MSFullscreenChange",b)}
function Td(a,b,c){Ed()?(a.style.marginLeft=a.style.marginRight=c+"px",a.style.marginTop=a.style.marginBottom=b+"px"):(a.style.paddingLeft=a.style.paddingRight=c+"px",a.style.paddingTop=a.style.paddingBottom=b+"px")}
function Ud(a,b){if(0!=b.sg||0!=b.fg){Sd(a);var c=b.Jh?innerWidth:screen.width,d=b.Jh?innerHeight:screen.height,e=a.getBoundingClientRect(),f=e.right-e.left;e=e.bottom-e.top;var h=Od(a),n=h[0];h=h[1];3==b.sg?(Td(a,(d-e)/2,(c-f)/2),c=f,d=e):2==b.sg&&(c*h<n*d?(f=h*c/n,Td(a,(d-f)/2,0),d=f):(f=n*d/h,Td(a,0,(c-f)/2),c=f));a.style.backgroundColor||(a.style.backgroundColor="black");document.body.style.backgroundColor||(document.body.style.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";
1==b.mh&&(a.style.Gg="pixelated");f=2==b.fg?devicePixelRatio:1;0!=b.fg&&(c=c*f|0,d=d*f|0,Rd(a,c,d),a.Af&&a.Af.lf.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.msRequestFullscreen)a.msRequestFullscreen();else if(a.mozRequestFullScreen)a.mozRequestFullScreen();else if(a.Og)a.Og();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return Hd()?-3:-1;b.sf&&Y(b.sf,37,0,b.eg);return 0}
function Vd(a){if(a.requestPointerLock)a.requestPointerLock();else if(a.Uf)a.Uf();else if(a.dg)a.dg();else if(a.Vf)a.Vf();else return document.body.requestPointerLock||document.body.Uf||document.body.dg||document.body.Vf?-3:-1;return 0}
function Wd(a,b){A[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)A[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)A[a+8*c+528>>3]="object"===typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)v[a+4*c+1040>>2]="object"===typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];v[a+1296>>2]=b.connected;v[a+1300>>2]=b.index;v[a+8>>2]=b.axes.length;v[a+12>>2]=b.buttons.length;G(b.id,a+1304,64);G(b.mapping,a+1368,64)}
function Xd(a,b,c){(a|0)===a&&(a=F(a));a=ub(a);if(a=k.preloadedImages[a]){var d=a.getContext("2d").getImageData(0,0,a.width,a.height),e=B(a.width*a.height*4);C.set(d.data,e);v[b>>2]=a.width;v[c>>2]=a.height;return e}return 0}var Yd=[];function Zd(a,b,c,d){for(var e=0;e<a;e++){var f=M[c](),h=f&&$c(d);f?(f.name=h,d[h]=f):T(1282);v[b+4*e>>2]=h}}
function $d(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&T(1280);return;case 36345:d=0;break;case 34466:var e=M.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=M.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":T(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:T(1280);return}else{if(e instanceof Float32Array||
e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:v[b+4*a>>2]=e[a];break;case 2:y[b+4*a>>2]=e[a];break;case 4:r[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(f){T(1280);l("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:T(1280);l("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:w=
[d>>>0,(x=d,1<=+Ba(x)?0<x?(Ca(+Da(x/4294967296),4294967295)|0)>>>0:~~+Ea((x-+(~~x>>>0))/4294967296)>>>0:0)];v[b>>2]=w[0];v[b+4>>2]=w[1];break;case 0:v[b>>2]=d;break;case 2:y[b>>2]=d;break;case 4:r[b>>0]=d?1:0}}else T(1281)}function ae(a){var b=Na(a)+1,c=B(b);G(a,c,b);return c}
function be(a,b,c,d){if(c)if(a=M.getUniform(P[a],Q[b]),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:v[c>>2]=a;break;case 2:y[c>>2]=a;break;default:throw"internal emscriptenWebGLGetUniform() error, bad type: "+d;}else for(b=0;b<a.length;b++)switch(d){case 0:v[c+4*b>>2]=a[b];break;case 2:y[c+4*b>>2]=a[b];break;default:throw"internal emscriptenWebGLGetUniform() error, bad type: "+d;}else T(1281)}
function ce(a,b,c,d){if(c)if(a=M.getVertexAttrib(a,b),34975==b)v[c>>2]=a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:v[c>>2]=a;break;case 2:y[c>>2]=a;break;case 5:v[c>>2]=Math.fround(a);break;default:throw"internal emscriptenWebGLGetVertexAttrib() error, bad type: "+d;}else for(b=0;b<a.length;b++)switch(d){case 0:v[c+4*b>>2]=a[b];break;case 2:y[c+4*b>>2]=a[b];break;case 5:v[c+4*b>>2]=Math.fround(a[b]);break;default:throw"internal emscriptenWebGLGetVertexAttrib() error, bad type: "+
d;}else T(1281)}var de={6402:1,6406:1,6407:3,6408:4,6409:1,6410:2,35904:3,35906:4},ee={5121:1,5123:2,5125:4,5126:4,32819:2,32820:2,33635:2,34042:4,36193:2};function fe(a,b,c,d,e){if(b=de[b]*ee[a]){var f=Zc;c=e+d*(c*b+f-1&-f);switch(a){case 5121:return C.subarray(e,c);case 5126:return y.subarray(e>>2,c>>2);case 5125:case 34042:return Qa.subarray(e>>2,c>>2);case 5123:case 33635:case 32819:case 32820:case 36193:return Pa.subarray(e>>1,c>>1);default:T(1280)}}else T(1280)}var ge=0;
function he(a,b,c,d){a|=0;b|=0;c|=0;d|=0;var e=0;ge=ge+1|0;for(v[a>>2]=ge;(e|0)<(d|0);){if(0==(v[c+(e<<3)>>2]|0))return v[c+(e<<3)>>2]=ge,v[c+((e<<3)+4)>>2]=b,v[c+((e<<3)+8)>>2]=0,wa=d|0,c|0;e=e+1|0}d=2*d|0;c=ie(c|0,8*(d+1|0)|0)|0;c=he(a|0,b|0,c|0,d|0)|0;wa=d|0;return c|0}function je(a,b){if(!Hd())return-1;a||(a="#canvas");a=V(a);return a?a.requestFullscreen||a.msRequestFullscreen||a.mozRequestFullScreen||a.Og||a.webkitRequestFullscreen?Cd&&Dd.Xe?Ud(a,b):b.ih?(zd(Ud,1,[a,b]),1):-2:-3:-4}
function ke(a,b,c,d,e,f){nd||(nd=B(256));a={target:V(a),Xe:!1,Ye:f,ef:d,ff:function(a){a=a||event;var c=a.target.id?a.target.id:"",f=nd;G(Gd(a.target),f+0,128);G(c,f+128,128);Y(d,e,f,b)&&a.preventDefault()},df:c};Fd(a)}
function le(a,b,c,d,e){od||(od=B(280));Fd({target:a,Xe:!1,Ye:e,ef:d,ff:function(a){a=a||event;var c=od,e=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,f=!!e;v[c>>2]=f;v[c+4>>2]=Hd();var q=f?e:sd,u=q&&q.id?q.id:"";G(Gd(q),c+8,128);G(u,c+136,128);v[c+264>>2]=q?q.clientWidth:0;v[c+268>>2]=q?q.clientHeight:0;v[c+272>>2]=screen.width;v[c+276>>2]=screen.height;f&&(sd=e);Y(d,19,c,b)&&a.preventDefault()},df:c})}
function me(a,b,c,d,e){Kd||(Kd=B(1432));b={target:V(2),Xe:!0,Ye:e,ef:c,ff:function(b){b=b||event;var e=Kd;Wd(e,b.gamepad);Y(c,d,e,a)&&b.preventDefault()},df:b};Fd(b)}
function ne(a,b,c,d,e,f){jd||(jd=B(164));a={target:V(a),Xe:Ed()?!1:!0,Ye:f,ef:d,ff:function(a){a=a||event;var c=jd;G(a.key?a.key:"",c+0,32);G(a.code?a.code:"",c+32,32);v[c+64>>2]=a.location;v[c+68>>2]=a.ctrlKey;v[c+72>>2]=a.shiftKey;v[c+76>>2]=a.altKey;v[c+80>>2]=a.metaKey;v[c+84>>2]=a.repeat;G(a.locale?a.locale:"",c+88,32);G(a.char?a.char:"",c+120,32);v[c+152>>2]=a.charCode;v[c+156>>2]=a.keyCode;v[c+160>>2]=a.which;Y(d,e,c,b)&&a.preventDefault()},df:c};Fd(a)}
function oe(a,b,c){A[a>>3]=window.performance&&window.performance.now?window.performance.now():Date.now();v[a+8>>2]=b.screenX;v[a+12>>2]=b.screenY;v[a+16>>2]=b.clientX;v[a+20>>2]=b.clientY;v[a+24>>2]=b.ctrlKey;v[a+28>>2]=b.shiftKey;v[a+32>>2]=b.altKey;v[a+36>>2]=b.metaKey;Aa[a+40>>1]=b.button;Aa[a+42>>1]=b.buttons;v[a+44>>2]=b.movementX||b.mozMovementX||b.webkitMovementX||b.screenX-td;v[a+48>>2]=b.movementY||b.mozMovementY||b.webkitMovementY||b.screenY-ud;if(k.canvas){var d=k.canvas.getBoundingClientRect();
v[a+60>>2]=b.clientX-d.left;v[a+64>>2]=b.clientY-d.top}else v[a+60>>2]=0,v[a+64>>2]=0;c?(d=c.getBoundingClientRect?c.getBoundingClientRect():{left:0,top:0},v[a+52>>2]=b.clientX-d.left,v[a+56>>2]=b.clientY-d.top):(v[a+52>>2]=0,v[a+56>>2]=0);"wheel"!==b.type&&"mousewheel"!==b.type&&(td=b.screenX,ud=b.screenY)}
function pe(a,b,c,d,e,f){kd||(kd=B(72));a=V(a);c={target:a,Xe:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,Ye:f,ef:d,ff:function(c){c=c||event;oe(kd,c,a);Y(d,e,kd,b)&&c.preventDefault()},df:c};Ed()&&"mousedown"==f&&(c.Xe=!1);Fd(c)}
function qe(a,b,c,d,e){pd||(pd=B(260));Fd({target:a,Xe:!1,Ye:e,ef:d,ff:function(a){a=a||event;var c=pd,e=document.pointerLockElement||document.Uh||document.Wh||document.Vh;v[c>>2]=!!e;var f=e&&e.id?e.id:"";G(Gd(e),c+4,128);G(f,c+132,128);Y(d,20,c,b)&&a.preventDefault()},df:c})}
function re(a,b,c,d){md||(md=B(36));a=V(a);Fd({target:a,Xe:!1,Ye:"resize",ef:d,ff:function(c){c=c||event;if(c.target==a){var e=0<pageXOffset||0<pageYOffset?[pageXOffset,pageYOffset]:"undefined"!==typeof document.documentElement.scrollLeft||"undefined"!==typeof document.documentElement.scrollTop?[document.documentElement.scrollLeft,document.documentElement.scrollTop]:[document.body.scrollLeft|0,document.body.scrollTop|0],h=md;v[h>>2]=c.detail;v[h+4>>2]=document.body.clientWidth;v[h+8>>2]=document.body.clientHeight;
v[h+12>>2]=innerWidth;v[h+16>>2]=innerHeight;v[h+20>>2]=outerWidth;v[h+24>>2]=outerHeight;v[h+28>>2]=e[0];v[h+32>>2]=e[1];Y(d,10,h,b)&&c.preventDefault()}},df:c})}
function se(a,b,c,d,e,f){rd||(rd=B(1684));a=V(a);Fd({target:a,Xe:"touchstart"==f||"touchend"==f,Ye:f,ef:d,ff:function(c){c=c||event;for(var f={},h=0;h<c.touches.length;++h){var q=c.touches[h];q.yg=!1;f[q.identifier]=q}for(h=0;h<c.changedTouches.length;++h)q=c.changedTouches[h],f[q.identifier]=q,q.yg=!0;for(h=0;h<c.targetTouches.length;++h)q=c.targetTouches[h],f[q.identifier].zh=!0;var u=q=rd;v[u+4>>2]=c.ctrlKey;v[u+8>>2]=c.shiftKey;v[u+12>>2]=c.altKey;v[u+16>>2]=c.metaKey;u+=20;var D=k.canvas?k.canvas.getBoundingClientRect():
void 0,J=a.getBoundingClientRect?a.getBoundingClientRect():{left:0,top:0},z=0;for(h in f){var E=f[h];v[u>>2]=E.identifier;v[u+4>>2]=E.screenX;v[u+8>>2]=E.screenY;v[u+12>>2]=E.clientX;v[u+16>>2]=E.clientY;v[u+20>>2]=E.pageX;v[u+24>>2]=E.pageY;v[u+28>>2]=E.yg;v[u+32>>2]=E.zh;D?(v[u+44>>2]=E.clientX-D.left,v[u+48>>2]=E.clientY-D.top):(v[u+44>>2]=0,v[u+48>>2]=0);v[u+36>>2]=E.clientX-J.left;v[u+40>>2]=E.clientY-J.top;u+=52;if(32<=++z)break}v[q>>2]=z;Y(d,e,q,b)&&c.preventDefault()},df:c})}
function te(a,b,c){var d=Md[1];qd||(qd=B(8));Fd({target:d,Xe:!1,Ye:"visibilitychange",ef:c,ff:function(b){b=b||event;var d=qd,e=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);v[d>>2]=document.hidden;v[d+4>>2]=e;Y(c,21,d,a)&&b.preventDefault()},df:b})}
function ue(a,b,c,d,e){function f(c){c=c||event;oe(ld,c,a);A[ld+72>>3]=c.wheelDeltaX||0;A[ld+80>>3]=-(c.wheelDeltaY||c.wheelDelta);A[ld+88>>3]=0;v[ld+96>>2]=0;Y(d,9,ld,b)&&c.preventDefault()}function h(c){c=c||event;var e=ld;oe(e,c,a);A[e+72>>3]=c.deltaX;A[e+80>>3]=c.deltaY;A[e+88>>3]=c.deltaZ;v[e+96>>2]=c.deltaMode;Y(d,9,e,b)&&c.preventDefault()}ld||(ld=B(104));Fd({target:a,Xe:!0,Ye:e,ef:d,ff:"wheel"==e?h:f,df:c})}var ve={};
function we(){if(!xe){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca},b;for(b in ve)a[b]=ve[b];var c=[];for(b in a)c.push(b+"="+a[b]);xe=c}return xe}var xe;function Ce(a){return 0===a%4&&(0!==a%100||0===a%400)}function De(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var Ee=[31,29,31,30,31,30,31,31,30,31,30,31],Fe=[31,28,31,30,31,30,31,31,30,31,30,31];
function Ge(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Ce(a.getFullYear())?Ee:Fe)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function He(a,b,c,d){function e(a,b,c){for(a="number"===typeof a?a.toString():a||"";a.length<b;)a=c[0]+a;return a}function f(a,b){return e(a,b,"0")}function h(a,b){function c(a){return 0>a?-1:0<a?1:0}var d;0===(d=c(a.getFullYear()-b.getFullYear()))&&0===(d=c(a.getMonth()-b.getMonth()))&&(d=c(a.getDate()-b.getDate()));return d}function n(a){switch(a.getDay()){case 0:return new Date(a.getFullYear()-1,11,29);case 1:return a;case 2:return new Date(a.getFullYear(),0,3);case 3:return new Date(a.getFullYear(),
0,2);case 4:return new Date(a.getFullYear(),0,1);case 5:return new Date(a.getFullYear()-1,11,31);case 6:return new Date(a.getFullYear()-1,11,30)}}function t(a){a=Ge(new Date(a.$e+1900,0,1),a.cg);var b=n(new Date(a.getFullYear()+1,0,4));return 0>=h(n(new Date(a.getFullYear(),0,4)),a)?0>=h(b,a)?a.getFullYear()+1:a.getFullYear():a.getFullYear()-1}var q=v[d+40>>2];d={Nh:v[d>>2],Mh:v[d+4>>2],ag:v[d+8>>2],If:v[d+12>>2],zf:v[d+16>>2],$e:v[d+20>>2],bg:v[d+24>>2],cg:v[d+28>>2],vi:v[d+32>>2],Lh:v[d+36>>2],
Oh:q?F(q):""};c=F(c);q={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var u in q)c=c.replace(new RegExp(u,"g"),q[u]);var D="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
J="January February March April May June July August September October November December".split(" ");q={"%a":function(a){return D[a.bg].substring(0,3)},"%A":function(a){return D[a.bg]},"%b":function(a){return J[a.zf].substring(0,3)},"%B":function(a){return J[a.zf]},"%C":function(a){return f((a.$e+1900)/100|0,2)},"%d":function(a){return f(a.If,2)},"%e":function(a){return e(a.If,2," ")},"%g":function(a){return t(a).toString().substring(2)},"%G":function(a){return t(a)},"%H":function(a){return f(a.ag,
2)},"%I":function(a){a=a.ag;0==a?a=12:12<a&&(a-=12);return f(a,2)},"%j":function(a){return f(a.If+De(Ce(a.$e+1900)?Ee:Fe,a.zf-1),3)},"%m":function(a){return f(a.zf+1,2)},"%M":function(a){return f(a.Mh,2)},"%n":function(){return"\n"},"%p":function(a){return 0<=a.ag&&12>a.ag?"AM":"PM"},"%S":function(a){return f(a.Nh,2)},"%t":function(){return"\t"},"%u":function(a){return a.bg||7},"%U":function(a){var b=new Date(a.$e+1900,0,1),c=0===b.getDay()?b:Ge(b,7-b.getDay());a=new Date(a.$e+1900,a.zf,a.If);return 0>
h(c,a)?f(Math.ceil((31-c.getDate()+(De(Ce(a.getFullYear())?Ee:Fe,a.getMonth()-1)-31)+a.getDate())/7),2):0===h(c,b)?"01":"00"},"%V":function(a){var b=n(new Date(a.$e+1900,0,4)),c=n(new Date(a.$e+1901,0,4)),d=Ge(new Date(a.$e+1900,0,1),a.cg);return 0>h(d,b)?"53":0>=h(c,d)?"01":f(Math.ceil((b.getFullYear()<a.$e+1900?a.cg+32-b.getDate():a.cg+1-b.getDate())/7),2)},"%w":function(a){return a.bg},"%W":function(a){var b=new Date(a.$e,0,1),c=1===b.getDay()?b:Ge(b,0===b.getDay()?1:7-b.getDay()+1);a=new Date(a.$e+
1900,a.zf,a.If);return 0>h(c,a)?f(Math.ceil((31-c.getDate()+(De(Ce(a.getFullYear())?Ee:Fe,a.getMonth()-1)-31)+a.getDate())/7),2):0===h(c,b)?"01":"00"},"%y":function(a){return(a.$e+1900).toString().substring(2)},"%Y":function(a){return a.$e+1900},"%z":function(a){a=a.Lh;var b=0<=a;a=Math.abs(a)/60;return(b?"+":"-")+String("0000"+(a/60*100+a%60)).slice(-4)},"%Z":function(a){return a.Oh},"%%":function(){return"%"}};for(u in q)0<=c.indexOf(u)&&(c=c.replace(new RegExp(u,"g"),q[u](d)));u=kb(c,!1);if(u.length>
b)return 0;r.set(u,a);return u.length-1}kc();Jb=Array(4096);Zb(I,"/");K("/tmp");K("/home");K("/home/web_user");
(function(){K("/dev");xb(259,{read:function(){return 0},write:function(a,b,c,h){return h}});ac("/dev/null",259);wb(1280,zb);wb(1536,Ab);ac("/dev/tty",1280);ac("/dev/tty1",1536);if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else if(fa)try{var c=require("crypto");b=function(){return c.randomBytes(1)[0]}}catch(d){}b||(b=function(){p("random_device")});rc("/dev","random",b);rc("/dev","urandom",b);
K("/dev/shm");K("/dev/shm/tmp")})();K("/proc");K("/proc/self");K("/proc/self/fd");Zb({kf:function(){var a=Cb("/proc/self","fd",16895,73);a.Te={lookup:function(a,c){var b=Hb[+c];if(!b)throw new H(8);a={parent:null,kf:{Ng:"fake"},Te:{readlink:function(){return b.path}}};return a.parent=a}};return a}},"/proc/self/fd");k.FS_createFolder=nc;k.FS_createPath=oc;k.FS_createDataFile=qc;k.FS_createPreloadedFile=vc;k.FS_createLazyFile=uc;k.FS_createLink=sc;k.FS_createDevice=rc;k.FS_unlink=cc;
fa?Ac=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?Ac=dateNow:"object"===typeof performance&&performance&&"function"===typeof performance.now?Ac=function(){return performance.now()}:Ac=Date.now;k.requestFullScreen=function(a,b,c){l("Module.requestFullScreen is deprecated. Please call Module.requestFullscreen instead.");k.requestFullScreen=k.requestFullscreen;g.Ug(a,b,c)};k.requestFullscreen=function(a,b,c){g.requestFullscreen(a,b,c)};
k.requestAnimationFrame=function(a){g.requestAnimationFrame(a)};k.setCanvasSize=function(a,b,c){g.Eh(a,b,c)};k.pauseMainLoop=function(){g.Re.pause()};k.resumeMainLoop=function(){g.Re.resume()};k.getUserMedia=function(){g.getUserMedia()};k.createContext=function(a,b,c,d){return g.createContext(a,b,c,d)};var M;ad=new Float32Array(256);for(var Ie=0;256>Ie;Ie++)bd[Ie]=ad.subarray(0,Ie+1);for(var Je=0;32>Je;Je++)Yd.push(Array(Je));
function kb(a,b){var c=Array(Na(a)+1);a=La(a,c,0,c.length);b&&(c.length=a);return c}
var $e={Wb:function(a){return B(a)},Ha:function(a){"uncaught_exception"in Ke?Ke.pf++:Ke.pf=1;throw a;},y:function(){},ga:function(){ob(63);return-1},x:function(a,b){yc=b;try{var c=zc();switch(L()){case 0:var d=L();return 0>d?-28:ec(c.path,c.flags,0,d).fd;case 1:case 2:return 0;case 3:return c.flags;case 4:return d=L(),c.flags|=d,0;case 12:return d=L(),Aa[d+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return ob(28),-1;default:return-28}}catch(e){return"undefined"!==typeof wc&&
e instanceof H||p(e),-e.hf}},ma:function(a,b){yc=b;try{var c=F(L()),d=L(),e=L();return ec(c,d,e).fd}catch(f){return"undefined"!==typeof wc&&f instanceof H||p(f),-f.hf}},la:function(a,b){yc=b;try{var c=zc(),d=L();switch(d){case 21509:case 21505:return c.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return c.tty?0:-59;case 21519:if(!c.tty)return-59;var e=L();return v[e>>2]=0;case 21520:return c.tty?-28:-59;case 21531:a=e=L();if(!c.Ue.vh)throw new H(59);return c.Ue.vh(c,
d,a);case 21523:return c.tty?0:-59;case 21524:return c.tty?0:-59;default:p("bad ioctl syscall "+d)}}catch(f){return"undefined"!==typeof wc&&f instanceof H||p(f),-f.hf}},fa:function(a,b){yc=b;try{var c=L(),d=L();if(-1===c||0===d)var e=-28;else{var f=xc[c];if(f&&d===f.hi){var h=Hb[f.fd],n=f.flags,t=new Uint8Array(C.subarray(c,c+d));h&&h.Ue.Wf&&h.Ue.Wf(h,t,0,d,n);xc[c]=null;f.ah&&Le(f.ji)}e=0}return e}catch(q){return"undefined"!==typeof wc&&q instanceof H||p(q),-q.hf}},j:function(){},m:function(){p()},
s:function(a,b){if(0===a)a=Date.now();else if(1===a&&(fa||"undefined"!==typeof dateNow||"object"===typeof performance&&performance&&"function"===typeof performance.now))a=Ac();else return ob(28),-1;v[b>>2]=a/1E3|0;v[b+4>>2]=a%1E3*1E6|0;return 0},pa:function(){return Bc.apply(null,arguments)},qa:function(){return Bc.apply(null,arguments)},D:function(){return Bc.apply(null,arguments)},Fa:function(a){if(12448==a)return N=12288,1;N=12300;return 0},Ka:function(a,b,c,d,e){if(62E3!=a)N=12296,c=0;else{if(b)for(;;){a=
v[b>>2];if(12321==a)O.alpha=0<v[b+4>>2];else if(12325==a)O.depth=0<v[b+4>>2];else if(12326==a)O.stencil=0<v[b+4>>2];else if(12337==a)a=v[b+4>>2],O.antialias=0<a;else if(12338==a)a=v[b+4>>2],O.antialias=1==a;else if(12544==a)O.ii=12547!=v[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(v[e>>2]=1),c&&0<d&&(v[c>>2]=62002),N=12288,c=1):(N=12300,c=0)}return c},wa:function(a,b,c,d){if(62E3!=a)return N=12296,0;for(a=1;;){b=v[d>>2];if(12440==b)a=v[d+4>>2];else if(12344==b)break;else return N=12292,0;d+=
8}if(2!=a)return N=12293,0;O.Kg=a-1;O.ki=0;Nc=Fc(k.canvas,O);if(0!=Nc)return N=12288,Hc(Nc),k.Rh=!0,g.Mg.forEach(function(a){a()}),Hc(null),62004;N=12297;return 0},ya:function(a,b){if(62E3!=a)return N=12296,0;if(62002!=b)return N=12293,0;N=12288;return 62006},xa:function(a,b){if(62E3!=a)return N=12296,0;if(62004!=b)return N=12294,0;a=Nc;Vc===Gc[a]&&(Vc=null);if("object"===typeof Id)for(var c=Gc[a].lf.canvas,d=0;d<xd.length;++d)xd[d].target!=c||yd(d--);Gc[a]&&Gc[a].lf.canvas&&(Gc[a].lf.canvas.Af=void 0);
Le(Gc[a]);Gc[a]=null;N=12288;Jc==b&&(Jc=0);return 1},za:function(a,b){if(62E3!=a)return N=12296,0;if(62006!=b)return N=12301,1;Kc==b&&(Kc=0);Lc==b&&(Lc=0);N=12288;return 1},Va:function(a,b,c,d){if(62E3!=a)return N=12296,0;if(62002!=b)return N=12293,0;if(!d)return N=12300,0;N=12288;switch(c){case 12320:return v[d>>2]=O.alpha?32:24,1;case 12321:return v[d>>2]=O.alpha?8:0,1;case 12322:return v[d>>2]=8,1;case 12323:return v[d>>2]=8,1;case 12324:return v[d>>2]=8,1;case 12325:return v[d>>2]=O.depth?24:
0,1;case 12326:return v[d>>2]=O.stencil?8:0,1;case 12327:return v[d>>2]=12344,1;case 12328:return v[d>>2]=62002,1;case 12329:return v[d>>2]=0,1;case 12330:return v[d>>2]=4096,1;case 12331:return v[d>>2]=16777216,1;case 12332:return v[d>>2]=4096,1;case 12333:return v[d>>2]=0,1;case 12334:return v[d>>2]=0,1;case 12335:return v[d>>2]=12344,1;case 12337:return v[d>>2]=O.antialias?4:0,1;case 12338:return v[d>>2]=O.antialias?1:0,1;case 12339:return v[d>>2]=4,1;case 12340:return v[d>>2]=12344,1;case 12341:case 12342:case 12343:return v[d>>
2]=-1,1;case 12345:case 12346:return v[d>>2]=0,1;case 12347:return v[d>>2]=0,1;case 12348:return v[d>>2]=1;case 12349:case 12350:return v[d>>2]=0,1;case 12351:return v[d>>2]=12430,1;case 12352:return v[d>>2]=4,1;case 12354:return v[d>>2]=0,1;default:return N=12292,0}},Y:function(){N=12288;return 62E3},va:function(){return N},Ga:function(a){return Me(a)},Ia:function(a,b,c){if(62E3==a)return b&&(v[b>>2]=1),c&&(v[c>>2]=4),Ic=!0,N=12288,1;N=12296;return 0},Aa:function(a,b,c,d){if(62E3!=a)return N=12296,
0;if(0!=d&&62004!=d)return N=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return N=12301,0;Hc(d?Nc:null);Jc=d;Lc=b;Kc=c;N=12288;return 1},ua:function(a,b){if(62E3!=a)return N=12296,0;N=12288;if(Mc[b])return Mc[b];switch(b){case 12371:a=Ia(kb("Emscripten"));break;case 12372:a=Ia(kb("1.4 Emscripten EGL"));break;case 12373:a=Ia(kb(""));break;case 12429:a=Ia(kb("OpenGL_ES"));break;default:return N=12300,0}return Mc[b]=a},Ba:function(){if(Ic)if(k.bf)if(k.bf.isContextLost())N=12302;else return N=12288,1;else N=
12290;else N=12289;return 0},Ca:function(a,b){if(62E3!=a)return N=12296,0;0==b?Cc(0,0):Cc(1,b);N=12288;return 1},Ja:function(a){if(62E3!=a)return N=12296,0;Lc=Kc=Jc=0;Ic=!1;N=12288;return 1},Ea:function(){return id.apply(null,arguments)},Da:function(){N=12288;return 1},d:function(a,b,c){a:for(mb.length=0;;){var d=C[b++];if(!d){b=mb;break a}100===d||102===d?(c=sa(c,8),mb.push(A[c>>3]),c+=8):105===d&&(c=sa(c,4),mb.push(v[c>>2]),c+=4)}return lb[a].apply(null,b)},Rd:function(){g.Re.pause();g.Re.jf=null},
ra:function(){if(!Hd())return-1;Ad(Ud);var a=Md[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.msExitFullscreen)a.msFullscreenElement&&a.msExitFullscreen();else if(a.mozCancelFullScreen)a.mozFullScreenElement&&a.mozCancelFullScreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;Ld.sf&&(Y(Ld.sf,37,0,Ld.eg),Ld=0);return 0},ta:function(){Ad(Vd);if(document.exitPointerLock)document.exitPointerLock();else if(document.Xg)document.Xg();
else if(document.pf)document.pf();else if(document.Yg)document.Yg();else return-1;return 0},n:function(){return devicePixelRatio||1},h:function(a,b,c){a=a?V(a):k.canvas;if(!a)return-4;a.getBoundingClientRect?(a=a.getBoundingClientRect(),A[b>>3]=a.right-a.left,A[c>>3]=a.bottom-a.top):(A[b>>3]=a.clientWidth,A[c>>3]=a.clientHeight);return 0},B:function(a,b){if(0>a||a>=Jd.length)return-5;if(!Jd[a])return-7;Wd(b,Jd[a]);return 0},oa:function(){return Jd.length},cd:Xd,Tc:function(a,b,c){a=k._fileno(a);return(a=
Hb[a])?Xd(a.path,b,c):0},Ad:function(a){M.activeTexture(a)},zd:function(a,b){M.attachShader(P[a],R[b])},Qd:function(a,b){M.cf.beginQueryEXT(a,S[b])},yd:function(a,b,c){M.bindAttribLocation(P[a],b,F(c))},xd:function(a,b){M.bindBuffer(a,Qc[b])},wd:function(a,b){M.bindFramebuffer(a,Rc[b])},vd:function(a,b){M.bindRenderbuffer(a,Sc[b])},ud:function(a,b){M.bindTexture(a,Tc[b])},Id:function(a){M.bindVertexArray(Uc[a])},td:function(a,b,c,d){M.blendColor(a,b,c,d)},sd:function(a){M.blendEquation(a)},rd:function(a,
b){M.blendEquationSeparate(a,b)},qd:function(a,b){M.blendFunc(a,b)},pd:function(a,b,c,d){M.blendFuncSeparate(a,b,c,d)},od:function(a,b,c,d){M.bufferData(a,c?C.subarray(c,c+b):b,d)},nd:function(a,b,c,d){M.bufferSubData(a,b,C.subarray(d,d+c))},md:function(a){return M.checkFramebufferStatus(a)},ld:function(a){M.clear(a)},kd:function(a,b,c,d){M.clearColor(a,b,c,d)},jd:function(a){M.clearDepth(a)},id:function(a){M.clearStencil(a)},hd:function(a,b,c,d){M.colorMask(!!a,!!b,!!c,!!d)},gd:function(a){M.compileShader(R[a])},
fd:function(a,b,c,d,e,f,h,n){M.compressedTexImage2D(a,b,c,d,e,f,n?C.subarray(n,n+h):null)},ed:function(a,b,c,d,e,f,h,n,t){M.compressedTexSubImage2D(a,b,c,d,e,f,h,t?C.subarray(t,t+n):null)},dd:function(a,b,c,d,e,f,h,n){M.copyTexImage2D(a,b,c,d,e,f,h,n)},bd:function(a,b,c,d,e,f,h,n){M.copyTexSubImage2D(a,b,c,d,e,f,h,n)},ad:function(){var a=$c(P),b=M.createProgram();b.name=a;P[a]=b;return a},$c:function(a){var b=$c(R);R[b]=M.createShader(a);return b},_c:function(a){M.cullFace(a)},Zc:function(a,b){for(var c=
0;c<a;c++){var d=v[b+4*c>>2],e=Qc[d];e&&(M.deleteBuffer(e),e.name=0,Qc[d]=null,d==gd&&(gd=0),d==hd&&(hd=0))}},Yc:function(a,b){for(var c=0;c<a;++c){var d=v[b+4*c>>2],e=Rc[d];e&&(M.deleteFramebuffer(e),e.name=0,Rc[d]=null)}},Xc:function(a){if(a){var b=P[a];b?(M.deleteProgram(b),b.name=0,P[a]=null,Xc[a]=null):T(1281)}},aa:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=S[d];e&&(M.cf.deleteQueryEXT(e),S[d]=null)}},Wc:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=Sc[d];e&&(M.deleteRenderbuffer(e),
e.name=0,Sc[d]=null)}},Vc:function(a){if(a){var b=R[a];b?(M.deleteShader(b),R[a]=null):T(1281)}},Uc:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=Tc[d];e&&(M.deleteTexture(e),e.name=0,Tc[d]=null)}},Hd:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2];M.deleteVertexArray(Uc[d]);Uc[d]=null}},Sc:function(a){M.depthFunc(a)},Rc:function(a){M.depthMask(!!a)},Qc:function(a,b){M.depthRange(a,b)},Pc:function(a,b){M.detachShader(P[a],R[b])},Oc:function(a){M.disable(a)},Nc:function(a){M.disableVertexAttribArray(a)},
Mc:function(a,b,c){M.drawArrays(a,b,c)},Dd:function(a,b,c,d){M.drawArraysInstanced(a,b,c,d)},Ed:function(a,b){for(var c=Yd[a],d=0;d<a;d++)c[d]=v[b+4*d>>2];M.drawBuffers(c)},Lc:function(a,b,c,d){M.drawElements(a,b,c,d)},Cd:function(a,b,c,d,e){M.drawElementsInstanced(a,b,c,d,e)},Kc:function(a){M.enable(a)},Jc:function(a){M.enableVertexAttribArray(a)},Pd:function(a){M.cf.endQueryEXT(a)},Ic:function(){M.finish()},Hc:function(){M.flush()},Gc:function(a,b,c,d){M.framebufferRenderbuffer(a,b,c,Sc[d])},Fc:function(a,
b,c,d,e){M.framebufferTexture2D(a,b,c,Tc[d],e)},Ec:function(a){M.frontFace(a)},Dc:function(a,b){Zd(a,b,"createBuffer",Qc)},Bc:function(a,b){Zd(a,b,"createFramebuffer",Rc)},ba:function(a,b){for(var c=0;c<a;c++){var d=M.cf.createQueryEXT();if(!d){for(T(1282);c<a;)v[b+4*c++>>2]=0;break}var e=$c(S);d.name=e;S[e]=d;v[b+4*c>>2]=e}},Ac:function(a,b){Zd(a,b,"createRenderbuffer",Sc)},zc:function(a,b){Zd(a,b,"createTexture",Tc)},Gd:function(a,b){Zd(a,b,"createVertexArray",Uc)},Cc:function(a){M.generateMipmap(a)},
yc:function(a,b,c,d,e,f,h){a=P[a];if(a=M.getActiveAttrib(a,b))c=0<c&&h?G(a.name,h,c):0,d&&(v[d>>2]=c),e&&(v[e>>2]=a.size),f&&(v[f>>2]=a.type)},xc:function(a,b,c,d,e,f,h){a=P[a];if(a=M.getActiveUniform(a,b))c=0<c&&h?G(a.name,h,c):0,d&&(v[d>>2]=c),e&&(v[e>>2]=a.size),f&&(v[f>>2]=a.type)},wc:function(a,b,c,d){a=M.getAttachedShaders(P[a]);var e=a.length;e>b&&(e=b);v[c>>2]=e;for(b=0;b<e;++b)v[d+4*b>>2]=R.indexOf(a[b])},vc:function(a,b){return M.getAttribLocation(P[a],F(b))},uc:function(a,b){$d(a,b,4)},
tc:function(a,b,c){c?v[c>>2]=M.getBufferParameter(a,b):T(1281)},sc:function(){var a=M.getError()||Pc;Pc=0;return a},rc:function(a,b){$d(a,b,2)},qc:function(a,b,c,d){a=M.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;v[d>>2]=a},pc:function(a,b){$d(a,b,0)},nc:function(a,b,c,d){a=M.getProgramInfoLog(P[a]);null===a&&(a="(unknown error)");b=0<b&&d?G(a,d,b):0;c&&(v[c>>2]=b)},oc:function(a,b,c){if(c)if(a>=Oc)T(1281);else{var d=Xc[a];if(d)if(35716==
b)a=M.getProgramInfoLog(P[a]),null===a&&(a="(unknown error)"),v[c>>2]=a.length+1;else if(35719==b)v[c>>2]=d.ng;else if(35722==b){if(-1==d.Df){a=P[a];var e=M.getProgramParameter(a,35721);for(b=d.Df=0;b<e;++b)d.Df=Math.max(d.Df,M.getActiveAttrib(a,b).name.length+1)}v[c>>2]=d.Df}else if(35381==b){if(-1==d.Ef)for(a=P[a],e=M.getProgramParameter(a,35382),b=d.Ef=0;b<e;++b)d.Ef=Math.max(d.Ef,M.getActiveUniformBlockName(a,b).length+1);v[c>>2]=d.Ef}else v[c>>2]=M.getProgramParameter(P[a],b);else T(1282)}else T(1281)},
Kd:function(a,b,c){if(c){a=M.cf.getQueryObjectEXT(S[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;w=[d>>>0,(x=d,1<=+Ba(x)?0<x?(Ca(+Da(x/4294967296),4294967295)|0)>>>0:~~+Ea((x-+(~~x>>>0))/4294967296)>>>0:0)];v[c>>2]=w[0];v[c+4>>2]=w[1]}else T(1281)},Md:function(a,b,c){if(c){a=M.cf.getQueryObjectEXT(S[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;v[c>>2]=d}else T(1281)},Jd:function(a,b,c){if(c){a=M.cf.getQueryObjectEXT(S[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;w=[d>>>0,(x=d,1<=+Ba(x)?0<x?(Ca(+Da(x/
4294967296),4294967295)|0)>>>0:~~+Ea((x-+(~~x>>>0))/4294967296)>>>0:0)];v[c>>2]=w[0];v[c+4>>2]=w[1]}else T(1281)},Ld:function(a,b,c){if(c){a=M.cf.getQueryObjectEXT(S[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;v[c>>2]=d}else T(1281)},Nd:function(a,b,c){c?v[c>>2]=M.cf.getQueryEXT(a,b):T(1281)},mc:function(a,b,c){c?v[c>>2]=M.getRenderbufferParameter(a,b):T(1281)},kc:function(a,b,c,d){a=M.getShaderInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?G(a,d,b):0;c&&(v[c>>2]=b)},jc:function(a,b,c,d){a=
M.getShaderPrecisionFormat(a,b);v[c>>2]=a.rangeMin;v[c+4>>2]=a.rangeMax;v[d>>2]=a.precision},ic:function(a,b,c,d){if(a=M.getShaderSource(R[a]))b=0<b&&d?G(a,d,b):0,c&&(v[c>>2]=b)},lc:function(a,b,c){c?35716==b?(a=M.getShaderInfoLog(R[a]),null===a&&(a="(unknown error)"),v[c>>2]=a.length+1):35720==b?(a=M.getShaderSource(R[a]),v[c>>2]=null===a||0==a.length?0:a.length+1):v[c>>2]=M.getShaderParameter(R[a],b):T(1281)},hc:function(a){if(Yc[a])return Yc[a];switch(a){case 7939:var b=M.getSupportedExtensions()||
[];b=b.concat(b.map(function(a){return"GL_"+a}));b=ae(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=M.getParameter(a))||T(1280);b=ae(b);break;case 7938:b=ae("OpenGL ES 2.0 ("+M.getParameter(M.VERSION)+")");break;case 35724:b=M.getParameter(M.SHADING_LANGUAGE_VERSION);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=ae(b);break;default:return T(1280),0}return Yc[a]=b},gc:function(a,b,c){c?
y[c>>2]=M.getTexParameter(a,b):T(1281)},fc:function(a,b,c){c?v[c>>2]=M.getTexParameter(a,b):T(1281)},cc:function(a,b){b=F(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=Xc[a]&&Xc[a].Vg[b])&&0<=c&&c<a[0]?a[1]+c:-1},ec:function(a,b,c){be(a,b,c,2)},dc:function(a,b,c){be(a,b,c,0)},$b:function(a,b,c){c?v[c>>2]=M.getVertexAttribOffset(a,b):T(1281)},bc:function(a,b,c){ce(a,b,c,2)},ac:function(a,b,c){ce(a,b,c,5)},_b:function(a,b){M.hint(a,
b)},Zb:function(a){return(a=Qc[a])?M.isBuffer(a):0},Yb:function(a){return M.isEnabled(a)},Xb:function(a){return(a=Rc[a])?M.isFramebuffer(a):0},Ub:function(a){return(a=P[a])?M.isProgram(a):0},$:function(a){return(a=S[a])?M.cf.isQueryEXT(a):0},Tb:function(a){return(a=Sc[a])?M.isRenderbuffer(a):0},Sb:function(a){return(a=R[a])?M.isShader(a):0},Rb:function(a){return(a=Tc[a])?M.isTexture(a):0},Fd:function(a){return(a=Uc[a])?M.isVertexArray(a):0},Qb:function(a){M.lineWidth(a)},Pb:function(a){M.linkProgram(P[a]);
var b=P[a];a=Xc[a]={Vg:{},ng:0,Df:-1,Ef:-1};for(var c=a.Vg,d=M.getProgramParameter(b,35718),e=0;e<d;++e){var f=M.getActiveUniform(b,e),h=f.name;a.ng=Math.max(a.ng,h.length+1);"]"==h.slice(-1)&&(h=h.slice(0,h.lastIndexOf("[")));var n=M.getUniformLocation(b,h);if(n){var t=$c(Q);c[h]=[f.size,t];Q[t]=n;for(var q=1;q<f.size;++q)n=M.getUniformLocation(b,h+"["+q+"]"),t=$c(Q),Q[t]=n}}},Ob:function(a,b){3317==a&&(Zc=b);M.pixelStorei(a,b)},Nb:function(a,b){M.polygonOffset(a,b)},Od:function(a,b){M.cf.queryCounterEXT(S[a],
b)},Mb:function(a,b,c,d,e,f,h){(h=fe(f,e,c,d,h))?M.readPixels(a,b,c,d,e,f,h):T(1280)},Lb:function(){},Jb:function(a,b,c,d){M.renderbufferStorage(a,b,c,d)},Ib:function(a,b){M.sampleCoverage(a,!!b)},Hb:function(a,b,c,d){M.scissor(a,b,c,d)},Gb:function(){T(1280)},Fb:function(a,b,c,d){for(var e="",f=0;f<b;++f){var h=d?v[d+4*f>>2]:-1;e+=F(v[c+4*f>>2],0>h?void 0:h)}M.shaderSource(R[a],e)},Eb:function(a,b,c){M.stencilFunc(a,b,c)},Db:function(a,b,c,d){M.stencilFuncSeparate(a,b,c,d)},Cb:function(a){M.stencilMask(a)},
Bb:function(a,b){M.stencilMaskSeparate(a,b)},Ab:function(a,b,c){M.stencilOp(a,b,c)},yb:function(a,b,c,d){M.stencilOpSeparate(a,b,c,d)},xb:function(a,b,c,d,e,f,h,n,t){M.texImage2D(a,b,c,d,e,f,h,n,t?fe(n,h,d,e,t):null)},wb:function(a,b,c){M.texParameterf(a,b,c)},vb:function(a,b,c){M.texParameterf(a,b,y[c>>2])},ub:function(a,b,c){M.texParameteri(a,b,c)},tb:function(a,b,c){M.texParameteri(a,b,v[c>>2])},sb:function(a,b,c,d,e,f,h,n,t){var q=null;t&&(q=fe(n,h,e,f,t));M.texSubImage2D(a,b,c,d,e,f,h,n,q)},
rb:function(a,b){M.uniform1f(Q[a],b)},qb:function(a,b,c){if(256>=b)for(var d=bd[b-1],e=0;e<b;++e)d[e]=y[c+4*e>>2];else d=y.subarray(c>>2,c+4*b>>2);M.uniform1fv(Q[a],d)},pb:function(a,b){M.uniform1i(Q[a],b)},ob:function(a,b,c){M.uniform1iv(Q[a],v.subarray(c>>2,c+4*b>>2))},nb:function(a,b,c){M.uniform2f(Q[a],b,c)},mb:function(a,b,c){if(256>=2*b)for(var d=bd[2*b-1],e=0;e<2*b;e+=2)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2];else d=y.subarray(c>>2,c+8*b>>2);M.uniform2fv(Q[a],d)},lb:function(a,b,c){M.uniform2i(Q[a],
b,c)},kb:function(a,b,c){M.uniform2iv(Q[a],v.subarray(c>>2,c+8*b>>2))},jb:function(a,b,c,d){M.uniform3f(Q[a],b,c,d)},ib:function(a,b,c){if(256>=3*b)for(var d=bd[3*b-1],e=0;e<3*b;e+=3)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2],d[e+2]=y[c+(4*e+8)>>2];else d=y.subarray(c>>2,c+12*b>>2);M.uniform3fv(Q[a],d)},hb:function(a,b,c,d){M.uniform3i(Q[a],b,c,d)},gb:function(a,b,c){M.uniform3iv(Q[a],v.subarray(c>>2,c+12*b>>2))},fb:function(a,b,c,d,e){M.uniform4f(Q[a],b,c,d,e)},db:function(a,b,c){if(256>=4*b)for(var d=
bd[4*b-1],e=0;e<4*b;e+=4)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2],d[e+2]=y[c+(4*e+8)>>2],d[e+3]=y[c+(4*e+12)>>2];else d=y.subarray(c>>2,c+16*b>>2);M.uniform4fv(Q[a],d)},cb:function(a,b,c,d,e){M.uniform4i(Q[a],b,c,d,e)},bb:function(a,b,c){M.uniform4iv(Q[a],v.subarray(c>>2,c+16*b>>2))},ab:function(a,b,c,d){if(256>=4*b)for(var e=bd[4*b-1],f=0;f<4*b;f+=4)e[f]=y[d+4*f>>2],e[f+1]=y[d+(4*f+4)>>2],e[f+2]=y[d+(4*f+8)>>2],e[f+3]=y[d+(4*f+12)>>2];else e=y.subarray(d>>2,d+16*b>>2);M.uniformMatrix2fv(Q[a],!!c,
e)},$a:function(a,b,c,d){if(256>=9*b)for(var e=bd[9*b-1],f=0;f<9*b;f+=9)e[f]=y[d+4*f>>2],e[f+1]=y[d+(4*f+4)>>2],e[f+2]=y[d+(4*f+8)>>2],e[f+3]=y[d+(4*f+12)>>2],e[f+4]=y[d+(4*f+16)>>2],e[f+5]=y[d+(4*f+20)>>2],e[f+6]=y[d+(4*f+24)>>2],e[f+7]=y[d+(4*f+28)>>2],e[f+8]=y[d+(4*f+32)>>2];else e=y.subarray(d>>2,d+36*b>>2);M.uniformMatrix3fv(Q[a],!!c,e)},_a:function(a,b,c,d){if(256>=16*b)for(var e=bd[16*b-1],f=0;f<16*b;f+=16)e[f]=y[d+4*f>>2],e[f+1]=y[d+(4*f+4)>>2],e[f+2]=y[d+(4*f+8)>>2],e[f+3]=y[d+(4*f+12)>>
2],e[f+4]=y[d+(4*f+16)>>2],e[f+5]=y[d+(4*f+20)>>2],e[f+6]=y[d+(4*f+24)>>2],e[f+7]=y[d+(4*f+28)>>2],e[f+8]=y[d+(4*f+32)>>2],e[f+9]=y[d+(4*f+36)>>2],e[f+10]=y[d+(4*f+40)>>2],e[f+11]=y[d+(4*f+44)>>2],e[f+12]=y[d+(4*f+48)>>2],e[f+13]=y[d+(4*f+52)>>2],e[f+14]=y[d+(4*f+56)>>2],e[f+15]=y[d+(4*f+60)>>2];else e=y.subarray(d>>2,d+64*b>>2);M.uniformMatrix4fv(Q[a],!!c,e)},Za:function(a){M.useProgram(P[a])},Ya:function(a){M.validateProgram(P[a])},Xa:function(a,b){M.vertexAttrib1f(a,b)},Wa:function(a,b){M.vertexAttrib1f(a,
y[b>>2])},Ua:function(a,b,c){M.vertexAttrib2f(a,b,c)},Ta:function(a,b){M.vertexAttrib2f(a,y[b>>2],y[b+4>>2])},Sa:function(a,b,c,d){M.vertexAttrib3f(a,b,c,d)},Ra:function(a,b){M.vertexAttrib3f(a,y[b>>2],y[b+4>>2],y[b+8>>2])},Qa:function(a,b,c,d,e){M.vertexAttrib4f(a,b,c,d,e)},Pa:function(a,b){M.vertexAttrib4f(a,y[b>>2],y[b+4>>2],y[b+8>>2],y[b+12>>2])},Bd:function(a,b){M.vertexAttribDivisor(a,b)},Oa:function(a,b,c,d,e,f){M.vertexAttribPointer(a,b,c,!!d,e,f)},Na:function(a,b,c,d){M.viewport(a,b,c,d)},
e:function(a,b){Z(a,b||1);throw"longjmp";},ca:function(a,b,c){C.set(C.subarray(b,b+c),a)},sa:function(a,b,c){var d={};d.sg=v[c>>2];d.fg=v[c+4>>2];d.mh=v[c+8>>2];d.ih=b;d.sf=v[c+12>>2];d.eg=v[c+16>>2];Ld=d;return je(a,d)},X:function(a,b){a||(a="#canvas");a=V(a);return a?a.requestPointerLock||a.Uf||a.dg||a.Vf?Cd&&Dd.Xe?Vd(a):b?(zd(Vd,2,[a]),1):-2:-1:-4},da:function(a){if(2147418112<a)return!1;for(var b=Math.max(r.length,16777216);b<a;)536870912>=b?b=Oa(2*b):b=Math.min(Oa((3*b+2147483648)/4),2147418112);
a:{try{Fa.grow(b-buffer.byteLength+65535>>16);Ra(Fa.buffer);var c=1;break a}catch(d){}c=void 0}return c?!0:!1},C:function(){return(Jd=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads():null)?0:-1},P:function(a,b,c,d){ke(a,b,c,d,12,"blur");return 0},k:Qd,t:function(a,b,c){a=a?V(a):k.canvas;if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},Q:function(a,b,c,d){ke(a,b,c,d,13,"focus");return 0},G:function(a,b,c,d){if(!Hd())return-1;
a=a?V(a):Md[1];if(!a)return-4;le(a,b,c,d,"fullscreenchange");le(a,b,c,d,"mozfullscreenchange");le(a,b,c,d,"webkitfullscreenchange");le(a,b,c,d,"msfullscreenchange");return 0},A:function(a,b,c){if(!navigator.getGamepads&&!navigator.webkitGetGamepads)return-1;me(a,b,c,26,"gamepadconnected");return 0},z:function(a,b,c){if(!navigator.getGamepads&&!navigator.webkitGetGamepads)return-1;me(a,b,c,27,"gamepaddisconnected");return 0},J:function(a,b,c,d){ne(a,b,c,d,2,"keydown");return 0},H:function(a,b,c,d){ne(a,
b,c,d,1,"keypress");return 0},I:function(a,b,c,d){ne(a,b,c,d,3,"keyup");return 0},Sd:Dc,V:function(a,b,c,d){pe(a,b,c,d,5,"mousedown");return 0},T:function(a,b,c,d){pe(a,b,c,d,33,"mouseenter");return 0},S:function(a,b,c,d){pe(a,b,c,d,34,"mouseleave");return 0},W:function(a,b,c,d){pe(a,b,c,d,8,"mousemove");return 0},U:function(a,b,c,d){pe(a,b,c,d,6,"mouseup");return 0},K:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.Uf||document.body.dg||document.body.Vf))return-1;
a=a?V(a):Md[1];if(!a)return-4;qe(a,b,c,d,"pointerlockchange");qe(a,b,c,d,"mozpointerlockchange");qe(a,b,c,d,"webkitpointerlockchange");qe(a,b,c,d,"mspointerlockchange");return 0},F:function(a,b,c,d){re(a,b,c,d);return 0},L:function(a,b,c,d){se(a,b,c,d,25,"touchcancel");return 0},N:function(a,b,c,d){se(a,b,c,d,23,"touchend");return 0},M:function(a,b,c,d){se(a,b,c,d,24,"touchmove");return 0},O:function(a,b,c,d){se(a,b,c,d,22,"touchstart");return 0},E:function(a,b,c){if(!Md[1])return-4;te(a,b,c);return 0},
R:function(a,b,c,d){a=V(a);return"undefined"!==typeof a.onwheel?(ue(a,b,c,d,"wheel"),0):"undefined"!==typeof a.onmousewheel?(ue(a,b,c,d,"mousewheel"),0):-1},ha:function(a,b){var c=0;we().forEach(function(d,e){var f=b+c;e=v[a+4*e>>2]=f;for(f=0;f<d.length;++f)r[e++>>0]=d.charCodeAt(f);r[e>>0]=0;c+=d.length+1});return 0},ia:function(a,b){var c=we();v[a>>2]=c.length;var d=0;c.forEach(function(a){d+=a.length+1});v[b>>2]=d;return 0},w:function(a){try{var b=zc(a);hc(b);return 0}catch(c){return"undefined"!==
typeof wc&&c instanceof H||p(c),c.hf}},ja:function(a,b,c,d){try{a:{for(var e=zc(a),f=a=0;f<c;f++){var h=v[b+(8*f+4)>>2],n=e,t=v[b+8*f>>2],q=h,u=void 0,D=r;if(0>q||0>u)throw new H(28);if(null===n.fd)throw new H(8);if(1===(n.flags&2097155))throw new H(8);if(16384===(n.node.mode&61440))throw new H(31);if(!n.Ue.read)throw new H(28);var J="undefined"!==typeof u;if(!J)u=n.position;else if(!n.seekable)throw new H(70);var z=n.Ue.read(n,D,t,q,u);J||(n.position+=z);var E=z;if(0>E){var pb=-1;break a}a+=E;if(E<
h)break}pb=a}v[d>>2]=pb;return 0}catch(Ma){return"undefined"!==typeof wc&&Ma instanceof H||p(Ma),Ma.hf}},La:function(a,b,c,d,e){try{var f=zc(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;ic(f,a,d);w=[f.position>>>0,(x=f.position,1<=+Ba(x)?0<x?(Ca(+Da(x/4294967296),4294967295)|0)>>>0:~~+Ea((x-+(~~x>>>0))/4294967296)>>>0:0)];v[e>>2]=w[0];v[e+4>>2]=w[1];f.lg&&0===a&&0===d&&(f.lg=null);return 0}catch(h){return"undefined"!==typeof wc&&h instanceof H||p(h),h.hf}},ka:function(a,
b,c,d){try{a:{for(var e=zc(a),f=a=0;f<c;f++){var h=jc(e,r,v[b+8*f>>2],v[b+(8*f+4)>>2],void 0);if(0>h){var n=-1;break a}a+=h}n=a}v[d>>2]=n;return 0}catch(t){return"undefined"!==typeof wc&&t instanceof H||p(t),t.hf}},a:function(){return wa|0},r:function(a){var b=Date.now();v[a>>2]=b/1E3|0;v[a+4>>2]=b%1E3*1E3|0;return 0},zb:Ne,v:Oe,l:Pe,p:Qe,q:Re,Vb:Se,Kb:Te,Z:Ue,Ma:Ve,g:We,o:Xe,_:Ye,u:Ze,memory:Fa,na:function(a,b){if(0===a)return ob(28),-1;var c=v[a>>2];a=v[a+4>>2];if(0>a||999999999<a||0>c)return ob(28),
-1;0!==b&&(v[b>>2]=0,v[b+4>>2]=0);b=(1E6*c+a/1E3)/1E3;if((ea||m)&&self.performance&&self.performance.now)for(c=self.performance.now();self.performance.now()-c<b;);else for(c=Date.now();Date.now()-c<b;);return 0},i:he,b:function(a){wa=a|0},f:function(){return 0},eb:function(){return 0},ea:function(a,b,c,d){return He(a,b,c,d)},table:Ga,c:function(a,b,c){a|=0;b|=0;c|=0;for(var d=0,e;(d|0)<(c|0);){e=v[b+(d<<3)>>2]|0;if(0==(e|0))break;if((e|0)==(a|0))return v[b+((d<<3)+4)>>2]|0;d=d+1|0}return 0}},af=function(){function a(a){k.asm=
a.exports;eb("wasm-instantiate")}function b(b){a(b.instance)}function c(a){return jb().then(function(a){return WebAssembly.instantiate(a,d)}).then(a,function(a){l("failed to asynchronously prepare wasm: "+a);p(a)})}var d={env:$e,wasi_unstable:$e};db("wasm-instantiate");if(k.instantiateWasm)try{return k.instantiateWasm(d,a)}catch(e){return l("Module.instantiateWasm callback failed with error: "+e),!1}(function(){if(xa||"function"!==typeof WebAssembly.instantiateStreaming||fb()||"function"!==typeof fetch)return c(b);
fetch(gb,{credentials:"same-origin"}).then(function(a){return WebAssembly.instantiateStreaming(a,d).then(b,function(a){l("wasm streaming compile failed: "+a);l("falling back to ArrayBuffer instantiation");c(b)})})})();return{}}();k.asm=af;var nb=k.___wasm_call_ctors=function(){return k.asm.Td.apply(null,arguments)};k._main=function(){return k.asm.Ud.apply(null,arguments)};
var B=k._malloc=function(){return k.asm.Vd.apply(null,arguments)},Le=k._free=function(){return k.asm.Wd.apply(null,arguments)},ie=k._realloc=function(){return k.asm.Xd.apply(null,arguments)};k.___errno_location=function(){return k.asm.Yd.apply(null,arguments)};k._fileno=function(){return k.asm.Zd.apply(null,arguments)};
var Z=k._setThrew=function(){return k.asm._d.apply(null,arguments)},Ke=k.__ZSt18uncaught_exceptionv=function(){return k.asm.$d.apply(null,arguments)},Me=k._emscripten_GetProcAddress=function(){return k.asm.ae.apply(null,arguments)},bf=k.dynCall_i=function(){return k.asm.be.apply(null,arguments)},cf=k.dynCall_ii=function(){return k.asm.ce.apply(null,arguments)},df=k.dynCall_iii=function(){return k.asm.de.apply(null,arguments)},Y=k.dynCall_iiii=function(){return k.asm.ee.apply(null,arguments)},ef=k.dynCall_iiiii=
function(){return k.asm.fe.apply(null,arguments)},ff=k.dynCall_iiiiii=function(){return k.asm.ge.apply(null,arguments)},gf=k.dynCall_iiiiiiiii=function(){return k.asm.he.apply(null,arguments)},hf=k.dynCall_iiiiiiiiii=function(){return k.asm.ie.apply(null,arguments)},jf=k.dynCall_jiji=function(){return k.asm.je.apply(null,arguments)},kf=k.dynCall_vi=function(){return k.asm.ke.apply(null,arguments)},lf=k.dynCall_vii=function(){return k.asm.le.apply(null,arguments)},mf=k.dynCall_viii=function(){return k.asm.me.apply(null,
arguments)},nf=k.dynCall_viiii=function(){return k.asm.ne.apply(null,arguments)},W=k.stackSave=function(){return k.asm.oe.apply(null,arguments)},Pd=k.stackAlloc=function(){return k.asm.pe.apply(null,arguments)},X=k.stackRestore=function(){return k.asm.qe.apply(null,arguments)};k.dynCall_v=function(){return k.asm.re.apply(null,arguments)};k.dynCall_viiiii=function(){return k.asm.se.apply(null,arguments)};k.dynCall_iiiiiii=function(){return k.asm.te.apply(null,arguments)};
k.dynCall_viiiiii=function(){return k.asm.ue.apply(null,arguments)};k.dynCall_iiiiiiii=function(){return k.asm.ve.apply(null,arguments)};k.dynCall_ji=function(){return k.asm.we.apply(null,arguments)};k.dynCall_iiiiidii=function(){return k.asm.xe.apply(null,arguments)};k.dynCall_viiiiiii=function(){return k.asm.ye.apply(null,arguments)};k.dynCall_viiiiiiiiiii=function(){return k.asm.ze.apply(null,arguments)};k.dynCall_iidiiii=function(){return k.asm.Ae.apply(null,arguments)};
k.dynCall_viijii=function(){return k.asm.Be.apply(null,arguments)};k.dynCall_iiiiij=function(){return k.asm.Ce.apply(null,arguments)};k.dynCall_iiiiid=function(){return k.asm.De.apply(null,arguments)};k.dynCall_iiiiijj=function(){return k.asm.Ee.apply(null,arguments)};k.dynCall_iiiiiijj=function(){return k.asm.Fe.apply(null,arguments)};k.dynCall_vffff=function(){return k.asm.Ge.apply(null,arguments)};k.dynCall_vf=function(){return k.asm.He.apply(null,arguments)};
k.dynCall_viiiiiiii=function(){return k.asm.Ie.apply(null,arguments)};k.dynCall_viiiiiiiii=function(){return k.asm.Je.apply(null,arguments)};k.dynCall_vff=function(){return k.asm.Ke.apply(null,arguments)};k.dynCall_vfi=function(){return k.asm.Le.apply(null,arguments)};k.dynCall_viif=function(){return k.asm.Me.apply(null,arguments)};k.dynCall_vif=function(){return k.asm.Ne.apply(null,arguments)};k.dynCall_viff=function(){return k.asm.Oe.apply(null,arguments)};
k.dynCall_vifff=function(){return k.asm.Pe.apply(null,arguments)};k.dynCall_viffff=function(){return k.asm.Qe.apply(null,arguments)};function Ze(a,b,c,d,e){var f=W();try{nf(a,b,c,d,e)}catch(h){X(f);if(h!==h+0&&"longjmp"!==h)throw h;Z(1,0)}}function Pe(a,b,c){var d=W();try{return df(a,b,c)}catch(e){X(d);if(e!==e+0&&"longjmp"!==e)throw e;Z(1,0)}}function Re(a,b,c,d,e){var f=W();try{return ef(a,b,c,d,e)}catch(h){X(f);if(h!==h+0&&"longjmp"!==h)throw h;Z(1,0)}}
function Qe(a,b,c,d){var e=W();try{return Y(a,b,c,d)}catch(f){X(e);if(f!==f+0&&"longjmp"!==f)throw f;Z(1,0)}}function We(a,b){var c=W();try{kf(a,b)}catch(d){X(c);if(d!==d+0&&"longjmp"!==d)throw d;Z(1,0)}}function Oe(a,b){var c=W();try{return cf(a,b)}catch(d){X(c);if(d!==d+0&&"longjmp"!==d)throw d;Z(1,0)}}function Ye(a,b,c,d){var e=W();try{mf(a,b,c,d)}catch(f){X(e);if(f!==f+0&&"longjmp"!==f)throw f;Z(1,0)}}
function Xe(a,b,c){var d=W();try{lf(a,b,c)}catch(e){X(d);if(e!==e+0&&"longjmp"!==e)throw e;Z(1,0)}}function Ue(a,b,c,d,e,f,h,n,t,q){var u=W();try{return hf(a,b,c,d,e,f,h,n,t,q)}catch(D){X(u);if(D!==D+0&&"longjmp"!==D)throw D;Z(1,0)}}function Se(a,b,c,d,e,f){var h=W();try{return ff(a,b,c,d,e,f)}catch(n){X(h);if(n!==n+0&&"longjmp"!==n)throw n;Z(1,0)}}function Te(a,b,c,d,e,f,h,n,t){var q=W();try{return gf(a,b,c,d,e,f,h,n,t)}catch(u){X(q);if(u!==u+0&&"longjmp"!==u)throw u;Z(1,0)}}
function Ne(a){var b=W();try{return bf(a)}catch(c){X(b);if(c!==c+0&&"longjmp"!==c)throw c;Z(1,0)}}function Ve(a,b,c,d,e){var f=W();try{return jf(a,b,c,d,e)}catch(h){X(f);if(h!==h+0&&"longjmp"!==h)throw h;Z(1,0)}}k.asm=af;k.getMemory=function(a){if(Za)var b=B(a);else b=v[48824],a=b+a+15&-16,a>r.length&&p(),v[48824]=a;return b};k.addRunDependency=db;k.removeRunDependency=eb;k.FS_createFolder=nc;k.FS_createPath=oc;k.FS_createDataFile=qc;k.FS_createPreloadedFile=vc;k.FS_createLazyFile=uc;
k.FS_createLink=sc;k.FS_createDevice=rc;k.FS_unlink=cc;k.calledRun=of;var of;function qa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}cb=function pf(){of||qf();of||(cb=pf)};
function qf(){function a(){if(!of&&(of=!0,k.calledRun=!0,!Ha)){Za=!0;k.noFSInit||lc||(lc=!0,kc(),k.stdin=k.stdin,k.stdout=k.stdout,k.stderr=k.stderr,k.stdin?rc("/dev","stdin",k.stdin):bc("/dev/tty","/dev/stdin"),k.stdout?rc("/dev","stdout",null,k.stdout):bc("/dev/tty","/dev/stdout"),k.stderr?rc("/dev","stderr",null,k.stderr):bc("/dev/tty1","/dev/stderr"),ec("/dev/stdin","r"),ec("/dev/stdout","w"),ec("/dev/stderr","w"));Ta(Va);Kb=!1;Ta(Wa);if(k.onRuntimeInitialized)k.onRuntimeInitialized();if(rf){var a=
k._main;try{var c=a(0,0);if(!ya||0!==c){if(!ya&&(Ha=!0,k.onExit))k.onExit(c);da(c,new qa(c))}}catch(d){d instanceof qa||("SimulateInfiniteLoop"==d?ya=!0:((a=d)&&"object"===typeof d&&d.stack&&(a=[d,d.stack]),l("exception thrown: "+a),da(1,d)))}finally{}}if(k.postRun)for("function"==typeof k.postRun&&(k.postRun=[k.postRun]);k.postRun.length;)a=k.postRun.shift(),Ya.unshift(a);Ta(Ya)}}if(!(0<ab)){if(k.preRun)for("function"==typeof k.preRun&&(k.preRun=[k.preRun]);k.preRun.length;)$a();Ta(Ua);0<ab||(k.setStatus?
(k.setStatus("Running..."),setTimeout(function(){setTimeout(function(){k.setStatus("")},1);a()},1)):a())}}k.run=qf;if(k.preInit)for("function"==typeof k.preInit&&(k.preInit=[k.preInit]);0<k.preInit.length;)k.preInit.pop()();var rf=!0;k.noInitialRun&&(rf=!1);ya=!0;qf();
